require: standard

inherit_gem:
  standard: config/base.yml

AllCops:
  SuggestExtensions: false
  Exclude:
    - "bin/**/*"
    - "tmp/**/*"
    - "lib/mkmf-rice.rb"

Style/GlobalVars:
  AllowedVariables:
    - '$qApp'
