# frozen_string_literal: true

require "bundler/gem_tasks"
GEMSPEC = Gem::Specification.load("rice.gemspec")

require "rubocop/rake_task"
RuboCop::RakeTask.new

require "rspec/core/rake_task"
RSpec::Core::RakeTask.new(:spec)

task default: %i[spec]
