# frozen_string_literal: true

source "https://rubygems.org"

gem "rake", "~> 13.0"
gem "ffi-clang", git: "https://github.com/souk4711/ffi-clang"
gem "ruby-bindgen", git: "https://github.com/souk4711/ruby-bindgen"
