# frozen_string_literal: true

source "https://rubygems.org"

gem "rake", "~> 13.0"
gem "rubocop"
gem "standard"
gem "solargraph"

gem "ffi-clang", git: "https://github.com/ioquatix/ffi-clang.git"
gem "ruby-bindgen", path: "../../ruby-bindgen"
