# frozen_string_literal: true

namespace :bindgen do
  def bindgen(extension:)
    require "ruby-bindgen"
    require_relative "ruby-bindgen-patch"

    clang_args = []
    clang_args << "-I/usr/lib/clang/20/include"
    clang_args << "-I./qt6include"
    clang_args << "-I./qt6include/#{extension}"
    clang_args << "-xc++"
    inputter = RubyBindgen::Inputter.new("qt6include/#{extension}", "q[a-z]*.h", ["*impl.h", "*helpers.h"])
    outputter = RubyBindgen::Outputter.new("qt6rice/#{extension}")
    parser = RubyBindgen::Parser.new(inputter, clang_args)
    format = RubyBindgen::Visitors::Rice.new(extension.downcase, outputter)
    parser.generate(format, parallel: true)
  end

  qt6libs = [
    "QtCore", "QtGui", "QtWidgets",
    "QtQml", "QtQuick", "QtQuickControls2", "QtQuickWidgets"
  ]
  qt6libs.each do |lib|
    desc "Generate Rice bindings for #{lib.sub("Qt", "libQt6")}"
    task lib.downcase do
      FileUtils.mkdir_p("qt6rice")
      FileUtils.rm_rf("qt6rice/#{lib}")
      bindgen(extension: lib)
      sh("clang-format -i -style=file --verbose qt6rice/#{lib}/*{hpp,cpp}")
    end
  end

  desc "Generate Rice bindings for libQt6"
  task :all do
    qt6libs.each { |lib| system("rake bindgen:#{lib.downcase}") }
  end
end

desc "Generate Rice bindings for qclass"
task :ext, [:qclass] do |_, args|
  name = args.qclass
  Dir["qt6rice/*/#{name.downcase}-rb.*"].each do |file|
    m = file.match("/(Qt.*)/(.*)")
    submod = m[1]
    copied = "../#{submod.downcase}/ext/qt6/#{submod.downcase}/#{m[2]}"
    sh("cp #{file} #{copied}")
    sh("sed -i 's/Init_Q#{name.downcase[1..]}(/Init_#{name.downcase}(Rice::Module rb_mQt6#{submod}/' #{copied}")
    sh("sed -i 's/define_class<#{name}\\(.*\\)>(/define_class_under<#{name}\\1>(rb_mQt6#{submod}, /' #{copied}")
  end
end

desc "Update libQt6 headers"
task :upinc do
  def upinc(pkg:)
    url = "https://mirror.rackspace.com/archlinux/extra/os/x86_64/#{pkg}-x86_64.pkg.tar.zst"
    inf = "tmp/downloads/#{pkg}.pkg.tar.zst"
    out = "tmp/downloads/#{pkg}"

    if File.exist?(inf)
      puts "found #{inf}"
    else
      sh "mkdir -p tmp/downloads"
      sh "curl -L --progress-bar -o #{inf} #{url}"
    end

    sh "mkdir -p #{out} && rm -rf #{out}/*"
    sh "tar --zstd -xf #{inf} --directory=#{out}"
    sh "cp -r #{out}/usr/include/qt6/. qt6include"
  end

  FileUtils.rm_rf("qt6include")
  upinc(pkg: "qt6-base-6.9.1-5")
  upinc(pkg: "qt6-declarative-6.9.1-2")
end

task :default do
  system("rake --tasks")
end
