# frozen_string_literal: true

module RubyQt6
  module QtCore
    # @see https://doc.qt.io/qt-6/qt.html
    module Qt
      rubyqt6_include_constants Qt, Qt::AlignmentFlag
      rubyqt6_include_constants Qt, Qt::AnchorPoint
      rubyqt6_include_constants Qt, Qt::ApplicationAttribute
      rubyqt6_include_constants Qt, Qt::ApplicationState
      rubyqt6_include_constants Qt, Qt::ArrowType
      rubyqt6_include_constants Qt, Qt::AspectRatioMode
      rubyqt6_include_constants Qt, Qt::Axis
      rubyqt6_include_constants Qt, Qt::BGMode
      rubyqt6_include_constants Qt, Qt::BrushStyle
      rubyqt6_include_constants Qt, Qt::CaseSensitivity
      rubyqt6_include_constants Qt, Qt::CheckState
      rubyqt6_include_constants Qt, Qt::ChecksumType
      rubyqt6_include_constants Qt, Qt::ClipOperation
      rubyqt6_include_constants Qt, Qt::ConnectionType
      rubyqt6_include_constants Qt, Qt::ContextMenuPolicy
      rubyqt6_include_constants Qt, Qt::CoordinateSystem
      rubyqt6_include_constants Qt, Qt::Corner
      rubyqt6_include_constants Qt, Qt::CursorMoveStyle
      rubyqt6_include_constants Qt, Qt::CursorShape
      rubyqt6_include_constants Qt, Qt::DateFormat
      rubyqt6_include_constants Qt, Qt::DayOfWeek
      rubyqt6_include_constants Qt, Qt::DockWidgetArea
      rubyqt6_include_constants Qt, Qt::DropAction
      rubyqt6_include_constants Qt, Qt::Edge
      rubyqt6_include_constants Qt, Qt::EnterKeyType
      rubyqt6_include_constants Qt, Qt::EventPriority
      rubyqt6_include_constants Qt, Qt::FillRule
      rubyqt6_include_constants Qt, Qt::FindChildOption
      rubyqt6_include_constants Qt, Qt::FocusPolicy
      rubyqt6_include_constants Qt, Qt::FocusReason
      rubyqt6_include_constants Qt, Qt::GestureFlag
      rubyqt6_include_constants Qt, Qt::GestureState
      rubyqt6_include_constants Qt, Qt::GestureType
      rubyqt6_include_constants Qt, Qt::GlobalColor
      rubyqt6_include_constants Qt, Qt::HitTestAccuracy
      rubyqt6_include_constants Qt, Qt::ImageConversionFlag
      rubyqt6_include_constants Qt, Qt::InputMethodHint
      rubyqt6_include_constants Qt, Qt::InputMethodQuery
      rubyqt6_include_constants Qt, Qt::ItemDataRole
      rubyqt6_include_constants Qt, Qt::ItemFlag
      rubyqt6_include_constants Qt, Qt::ItemSelectionMode
      rubyqt6_include_constants Qt, Qt::ItemSelectionOperation
      rubyqt6_include_constants Qt, Qt::Key
      rubyqt6_include_constants Qt, Qt::KeyboardModifier
      rubyqt6_include_constants Qt, Qt::LayoutDirection
      rubyqt6_include_constants Qt, Qt::MaskMode
      rubyqt6_include_constants Qt, Qt::MatchFlag
      rubyqt6_include_constants Qt, Qt::Modifier
      rubyqt6_include_constants Qt, Qt::MouseButton
      rubyqt6_include_constants Qt, Qt::MouseEventFlag
      rubyqt6_include_constants Qt, Qt::MouseEventSource
      rubyqt6_include_constants Qt, Qt::NativeGestureType
      rubyqt6_include_constants Qt, Qt::NavigationMode
      rubyqt6_include_constants Qt, Qt::Orientation
      rubyqt6_include_constants Qt, Qt::PenCapStyle
      rubyqt6_include_constants Qt, Qt::PenJoinStyle
      rubyqt6_include_constants Qt, Qt::PenStyle
      rubyqt6_include_constants Qt, Qt::ScreenOrientation
      rubyqt6_include_constants Qt, Qt::ScrollBarPolicy
      rubyqt6_include_constants Qt, Qt::ScrollPhase
      rubyqt6_include_constants Qt, Qt::ShortcutContext
      rubyqt6_include_constants Qt, Qt::SizeHint
      rubyqt6_include_constants Qt, Qt::SizeMode
      rubyqt6_include_constants Qt, Qt::SortOrder
      rubyqt6_include_constants Qt, Qt::SplitBehaviorFlags
      rubyqt6_include_constants Qt, Qt::TabFocusBehavior
      rubyqt6_include_constants Qt, Qt::TextElideMode
      rubyqt6_include_constants Qt, Qt::TextFlag
      rubyqt6_include_constants Qt, Qt::TextFormat
      rubyqt6_include_constants Qt, Qt::TextInteractionFlag
      rubyqt6_include_constants Qt, Qt::TileRule
      rubyqt6_include_constants Qt, Qt::TimeSpec
      rubyqt6_include_constants Qt, Qt::TimerType
      rubyqt6_include_constants Qt, Qt::ToolBarArea
      rubyqt6_include_constants Qt, Qt::ToolButtonStyle
      rubyqt6_include_constants Qt, Qt::TouchPointState
      rubyqt6_include_constants Qt, Qt::TransformationMode
      rubyqt6_include_constants Qt, Qt::UIEffect
      rubyqt6_include_constants Qt, Qt::WhiteSpaceMode
      rubyqt6_include_constants Qt, Qt::WidgetAttribute
      rubyqt6_include_constants Qt, Qt::WindowFrameSection
      rubyqt6_include_constants Qt, Qt::WindowModality
      rubyqt6_include_constants Qt, Qt::WindowState
      rubyqt6_include_constants Qt, Qt::WindowType
    end
  end
end
