#include "qevent-rb.hpp"
#include <qevent.h>

using namespace Rice;

Rice::Class rb_cQActionEvent;
Rice::Class rb_cQApplicationStateChangeEvent;
Rice::Class rb_cQChildWindowEvent;
Rice::Class rb_cQCloseEvent;
Rice::Class rb_cQContextMenuEvent;
Rice::Class rb_cQDragEnterEvent;
Rice::Class rb_cQDragLeaveEvent;
Rice::Class rb_cQDragMoveEvent;
Rice::Class rb_cQDropEvent;
Rice::Class rb_cQEnterEvent;
Rice::Class rb_cQExposeEvent;
Rice::Class rb_cQFileOpenEvent;
Rice::Class rb_cQFocusEvent;
Rice::Class rb_cQHelpEvent;
Rice::Class rb_cQHideEvent;
Rice::Class rb_cQHoverEvent;
Rice::Class rb_cQIconDragEvent;
Rice::Class rb_cQInputEvent;
Rice::Class rb_cQInputMethodEvent;
Rice::Class rb_cQInputMethodEventAttribute;
Rice::Class rb_cQInputMethodQueryEvent;
Rice::Class rb_cQKeyEvent;
Rice::Class rb_cQMouseEvent;
Rice::Class rb_cQMoveEvent;
Rice::Class rb_cQNativeGestureEvent;
Rice::Class rb_cQPaintEvent;
Rice::Class rb_cQPlatformSurfaceEvent;
Rice::Class rb_cQPointerEvent;
Rice::Class rb_cQResizeEvent;
Rice::Class rb_cQScreenOrientationChangeEvent;
Rice::Class rb_cQScrollEvent;
Rice::Class rb_cQScrollPrepareEvent;
Rice::Class rb_cQShortcutEvent;
Rice::Class rb_cQShowEvent;
Rice::Class rb_cQSinglePointEvent;
Rice::Class rb_cQStatusTipEvent;
Rice::Class rb_cQTabletEvent;
Rice::Class rb_cQToolBarChangeEvent;
Rice::Class rb_cQTouchEvent;
Rice::Class rb_cQWhatsThisClickedEvent;
Rice::Class rb_cQWheelEvent;
Rice::Class rb_cQWindowStateChangeEvent;

void Init_qevent(Rice::Module rb_mQt6QtGui)
{
    rb_cQActionEvent = define_class_under<QActionEvent, QEvent>(rb_mQt6QtGui, "QActionEvent");
    rb_cQApplicationStateChangeEvent = define_class_under<QApplicationStateChangeEvent, QEvent>(rb_mQt6QtGui, "QApplicationStateChangeEvent");
    rb_cQChildWindowEvent = define_class_under<QChildWindowEvent, QEvent>(rb_mQt6QtGui, "QChildWindowEvent");
    rb_cQCloseEvent = define_class_under<QCloseEvent, QEvent>(rb_mQt6QtGui, "QCloseEvent");
    rb_cQContextMenuEvent = define_class_under<QContextMenuEvent, QInputEvent>(rb_mQt6QtGui, "QContextMenuEvent");
    rb_cQDragEnterEvent = define_class_under<QDragEnterEvent, QDragMoveEvent>(rb_mQt6QtGui, "QDragEnterEvent");
    rb_cQDragLeaveEvent = define_class_under<QDragLeaveEvent, QEvent>(rb_mQt6QtGui, "QDragLeaveEvent");
    rb_cQDragMoveEvent = define_class_under<QDragMoveEvent, QDropEvent>(rb_mQt6QtGui, "QDragMoveEvent");
    rb_cQDropEvent = define_class_under<QDropEvent, QEvent>(rb_mQt6QtGui, "QDropEvent");
    rb_cQEnterEvent = define_class_under<QEnterEvent, QSinglePointEvent>(rb_mQt6QtGui, "QEnterEvent");
    rb_cQExposeEvent = define_class_under<QExposeEvent, QEvent>(rb_mQt6QtGui, "QExposeEvent");
    rb_cQFileOpenEvent = define_class_under<QFileOpenEvent, QEvent>(rb_mQt6QtGui, "QFileOpenEvent");
    rb_cQFocusEvent = define_class_under<QFocusEvent, QEvent>(rb_mQt6QtGui, "QFocusEvent");
    rb_cQHelpEvent = define_class_under<QHelpEvent, QEvent>(rb_mQt6QtGui, "QHelpEvent");
    rb_cQHideEvent = define_class_under<QHideEvent, QEvent>(rb_mQt6QtGui, "QHideEvent");
    rb_cQHoverEvent = define_class_under<QHoverEvent, QSinglePointEvent>(rb_mQt6QtGui, "QHoverEvent");
    rb_cQIconDragEvent = define_class_under<QIconDragEvent, QEvent>(rb_mQt6QtGui, "QIconDragEvent");
    rb_cQInputEvent = define_class_under<QInputEvent, QEvent>(rb_mQt6QtGui, "QInputEvent");
    rb_cQInputMethodEventAttribute = define_class_under<QInputMethodEvent::Attribute>(rb_cQInputMethodEvent, "Attribute");
    rb_cQInputMethodEvent = define_class_under<QInputMethodEvent, QEvent>(rb_mQt6QtGui, "QInputMethodEvent");
    rb_cQInputMethodQueryEvent = define_class_under<QInputMethodQueryEvent, QEvent>(rb_mQt6QtGui, "QInputMethodQueryEvent");
    rb_cQKeyEvent = define_class_under<QKeyEvent, QInputEvent>(rb_mQt6QtGui, "QKeyEvent");
    rb_cQMouseEvent = define_class_under<QMouseEvent, QSinglePointEvent>(rb_mQt6QtGui, "QMouseEvent");
    rb_cQMoveEvent = define_class_under<QMoveEvent, QEvent>(rb_mQt6QtGui, "QMoveEvent");
    rb_cQNativeGestureEvent = define_class_under<QNativeGestureEvent, QSinglePointEvent>(rb_mQt6QtGui, "QNativeGestureEvent");
    rb_cQPaintEvent = define_class_under<QPaintEvent, QEvent>(rb_mQt6QtGui, "QPaintEvent");
    rb_cQPlatformSurfaceEvent = define_class_under<QPlatformSurfaceEvent, QEvent>(rb_mQt6QtGui, "QPlatformSurfaceEvent");
    rb_cQPointerEvent = define_class_under<QPointerEvent, QInputEvent>(rb_mQt6QtGui, "QPointerEvent");
    rb_cQResizeEvent = define_class_under<QResizeEvent, QEvent>(rb_mQt6QtGui, "QResizeEvent");
    rb_cQScreenOrientationChangeEvent = define_class_under<QScreenOrientationChangeEvent, QEvent>(rb_mQt6QtGui, "QScreenOrientationChangeEvent");
    rb_cQScrollEvent = define_class_under<QScrollEvent, QEvent>(rb_mQt6QtGui, "QScrollEvent");
    rb_cQScrollPrepareEvent = define_class_under<QScrollPrepareEvent, QEvent>(rb_mQt6QtGui, "QScrollPrepareEvent");
    rb_cQShortcutEvent =define_class_under<QShortcutEvent, QEvent>(rb_mQt6QtGui, "QShortcutEvent");
    rb_cQShowEvent = define_class_under<QShowEvent, QEvent>(rb_mQt6QtGui, "QShowEvent");
    rb_cQSinglePointEvent = define_class_under<QSinglePointEvent, QPointerEvent>(rb_mQt6QtGui, "QSinglePointEvent");
    rb_cQStatusTipEvent = define_class_under<QStatusTipEvent, QEvent>(rb_mQt6QtGui, "QStatusTipEvent");
    rb_cQTabletEvent = define_class_under<QTabletEvent, QSinglePointEvent>(rb_mQt6QtGui, "QTabletEvent");
    rb_cQToolBarChangeEvent = define_class_under<QToolBarChangeEvent, QEvent>(rb_mQt6QtGui, "QToolBarChangeEvent");
    rb_cQTouchEvent = define_class_under<QTouchEvent, QPointerEvent>(rb_mQt6QtGui, "QTouchEvent");
    rb_cQWhatsThisClickedEvent = define_class_under<QWhatsThisClickedEvent, QEvent>(rb_mQt6QtGui, "QWhatsThisClickedEvent");
    rb_cQWheelEvent = define_class_under<QWheelEvent, QSinglePointEvent>(rb_mQt6QtGui, "QWheelEvent");
    rb_cQWindowStateChangeEvent = define_class_under<QWindowStateChangeEvent, QEvent>(rb_mQt6QtGui, "QWindowStateChangeEvent");
}
