#include "qicon-rb.hpp"
#include <qicon.h>

#include <QPainter>
#include <QWindow>

using namespace Rice;

Rice::Class rb_cQIcon;

void Init_qicon(Rice::Module rb_mQt6QtGui)
{
    rb_cQIcon =
        // RubyQt6::QtGui::QIcon
        define_class_under<QIcon>(rb_mQt6QtGui, "QIcon")
            // Constructor
            .define_constructor(Constructor<QIcon, const QString &>(), Arg("filename"))
            .define_constructor(Constructor<QIcon, const QPixmap &>(), Arg("pixmap"))
            // Public Functions
            .define_method<QSize (QIcon::*)(const QSize &, QIcon::Mode, QIcon::State) const>("actual_size", &QIcon::actualSize, Arg("size"), Arg("mode") = static_cast<QIcon::Mode>(QIcon::Mode::Normal), Arg("state") = static_cast<QIcon::State>(QIcon::State::Off))
            .define_method("add_file", &QIcon::addFile, Arg("file_name"), Arg("size") = static_cast<const QSize &>(QSize()), Arg("mode") = static_cast<QIcon::Mode>(QIcon::Mode::Normal), Arg("state") = static_cast<QIcon::State>(QIcon::State::Off))
            .define_method("add_pixmap", &QIcon::addPixmap, Arg("pixmap"), Arg("mode") = static_cast<QIcon::Mode>(QIcon::Mode::Normal), Arg("state") = static_cast<QIcon::State>(QIcon::State::Off))
            .define_method("available_sizes", &QIcon::availableSizes, Arg("mode") = static_cast<QIcon::Mode>(QIcon::Mode::Normal), Arg("state") = static_cast<QIcon::State>(QIcon::State::Off))
            .define_method("cache_key", &QIcon::cacheKey)
            .define_method("detach", &QIcon::detach)
            .define_method("detached?", &QIcon::isDetached)
            .define_method("mask?", &QIcon::isMask)
            .define_method("null?", &QIcon::isNull)
            .define_method("name", &QIcon::name)
            .define_method<void (QIcon::*)(QPainter *, const QRect &, Qt::Alignment, QIcon::Mode, QIcon::State) const>("paint", &QIcon::paint, Arg("painter"), Arg("rect"), Arg("alignment") = static_cast<Qt::Alignment>(Qt::AlignCenter), Arg("mode") = static_cast<QIcon::Mode>(QIcon::Mode::Normal), Arg("state") = static_cast<QIcon::State>(QIcon::State::Off))
            .define_method<void (QIcon::*)(QPainter *, int, int, int, int, Qt::Alignment, QIcon::Mode, QIcon::State) const>("paint", &QIcon::paint, Arg("painter"), Arg("x"), Arg("y"), Arg("w"), Arg("h"), Arg("alignment") = static_cast<Qt::Alignment>(Qt::AlignCenter), Arg("mode") = static_cast<QIcon::Mode>(QIcon::Mode::Normal), Arg("state") = static_cast<QIcon::State>(QIcon::State::Off))
            .define_method<QPixmap (QIcon::*)(const QSize &, QIcon::Mode, QIcon::State) const>("pixmap", &QIcon::pixmap, Arg("size"), Arg("mode") = static_cast<QIcon::Mode>(QIcon::Mode::Normal), Arg("state") = static_cast<QIcon::State>(QIcon::State::Off))
            .define_method<QPixmap (QIcon::*)(const QSize &, qreal, QIcon::Mode, QIcon::State) const>("pixmap", &QIcon::pixmap, Arg("size"), Arg("device_pixel_ratio"), Arg("mode") = static_cast<QIcon::Mode>(QIcon::Mode::Normal), Arg("state") = static_cast<QIcon::State>(QIcon::State::Off))
            .define_method<QPixmap (QIcon::*)(int, QIcon::Mode, QIcon::State) const>("pixmap", &QIcon::pixmap, Arg("extent"), Arg("mode") = static_cast<QIcon::Mode>(QIcon::Mode::Normal), Arg("state") = static_cast<QIcon::State>(QIcon::State::Off))
            .define_method<QPixmap (QIcon::*)(int, int, QIcon::Mode, QIcon::State) const>("pixmap", &QIcon::pixmap, Arg("w"), Arg("h"), Arg("mode") = static_cast<QIcon::Mode>(QIcon::Mode::Normal), Arg("state") = static_cast<QIcon::State>(QIcon::State::Off))
            .define_method("set_is_mask", &QIcon::setIsMask, Arg("is_mask"))
            // Static Public Members
            .define_singleton_function("fallback_search_paths", &QIcon::fallbackSearchPaths)
            .define_singleton_function("fallback_theme_name", &QIcon::fallbackThemeName)
            .define_singleton_function<QIcon (*)(QIcon::ThemeIcon)>("from_theme", &QIcon::fromTheme, Arg("icon"))
            .define_singleton_function<QIcon (*)(QIcon::ThemeIcon, const QIcon &)>("from_theme", &QIcon::fromTheme, Arg("icon"), Arg("fallback"))
            .define_singleton_function<QIcon (*)(const QString &)>("from_theme", &QIcon::fromTheme, Arg("name"))
            .define_singleton_function<QIcon (*)(const QString &, const QIcon &)>("from_theme", &QIcon::fromTheme, Arg("name"), Arg("fallback"))
            .define_singleton_function<bool (*)(QIcon::ThemeIcon)>("has_theme_icon", &QIcon::hasThemeIcon, Arg("icon"))
            .define_singleton_function<bool (*)(const QString &)>("has_theme_icon", &QIcon::hasThemeIcon, Arg("name"))
            .define_singleton_function("set_fallback_search_paths", &QIcon::setFallbackSearchPaths, Arg("paths"))
            .define_singleton_function("set_fallback_theme_name", &QIcon::setFallbackThemeName, Arg("name"))
            .define_singleton_function("set_theme_name", &QIcon::setThemeName, Arg("path"))
            .define_singleton_function("set_theme_search_paths", &QIcon::setThemeSearchPaths, Arg("searchpath"))
            .define_singleton_function("theme_name", &QIcon::themeName)
            .define_singleton_function("theme_search_paths", &QIcon::themeSearchPaths);

    Enum<QIcon::Mode> rb_cQIconMode =
        // RubyQt6::QtGui::QIcon::Mode
        define_enum_under<QIcon::Mode>("Mode", rb_cQIcon)
            .define_value("Normal", QIcon::Mode::Normal)
            .define_value("Disabled", QIcon::Mode::Disabled)
            .define_value("Active", QIcon::Mode::Active)
            .define_value("Selected", QIcon::Mode::Selected);

    Enum<QIcon::State> rb_cQIconState =
        // RubyQt6::QtGui::QIcon::State
        define_enum_under<QIcon::State>("State", rb_cQIcon)
            .define_value("On", QIcon::State::On)
            .define_value("Off", QIcon::State::Off);

    Enum<QIcon::ThemeIcon> rb_cQIconThemeIcon =
        // RubyQt6::QtGui::QIcon::ThemeIcon
        define_enum_under<QIcon::ThemeIcon>("ThemeIcon", rb_cQIcon)
            .define_value("AddressBookNew", QIcon::ThemeIcon::AddressBookNew)
            .define_value("ApplicationExit", QIcon::ThemeIcon::ApplicationExit)
            .define_value("AppointmentNew", QIcon::ThemeIcon::AppointmentNew)
            .define_value("CallStart", QIcon::ThemeIcon::CallStart)
            .define_value("CallStop", QIcon::ThemeIcon::CallStop)
            .define_value("ContactNew", QIcon::ThemeIcon::ContactNew)
            .define_value("DocumentNew", QIcon::ThemeIcon::DocumentNew)
            .define_value("DocumentOpen", QIcon::ThemeIcon::DocumentOpen)
            .define_value("DocumentOpenRecent", QIcon::ThemeIcon::DocumentOpenRecent)
            .define_value("DocumentPageSetup", QIcon::ThemeIcon::DocumentPageSetup)
            .define_value("DocumentPrint", QIcon::ThemeIcon::DocumentPrint)
            .define_value("DocumentPrintPreview", QIcon::ThemeIcon::DocumentPrintPreview)
            .define_value("DocumentProperties", QIcon::ThemeIcon::DocumentProperties)
            .define_value("DocumentRevert", QIcon::ThemeIcon::DocumentRevert)
            .define_value("DocumentSave", QIcon::ThemeIcon::DocumentSave)
            .define_value("DocumentSaveAs", QIcon::ThemeIcon::DocumentSaveAs)
            .define_value("DocumentSend", QIcon::ThemeIcon::DocumentSend)
            .define_value("EditClear", QIcon::ThemeIcon::EditClear)
            .define_value("EditCopy", QIcon::ThemeIcon::EditCopy)
            .define_value("EditCut", QIcon::ThemeIcon::EditCut)
            .define_value("EditDelete", QIcon::ThemeIcon::EditDelete)
            .define_value("EditFind", QIcon::ThemeIcon::EditFind)
            .define_value("EditPaste", QIcon::ThemeIcon::EditPaste)
            .define_value("EditRedo", QIcon::ThemeIcon::EditRedo)
            .define_value("EditSelectAll", QIcon::ThemeIcon::EditSelectAll)
            .define_value("EditUndo", QIcon::ThemeIcon::EditUndo)
            .define_value("FolderNew", QIcon::ThemeIcon::FolderNew)
            .define_value("FormatIndentLess", QIcon::ThemeIcon::FormatIndentLess)
            .define_value("FormatIndentMore", QIcon::ThemeIcon::FormatIndentMore)
            .define_value("FormatJustifyCenter", QIcon::ThemeIcon::FormatJustifyCenter)
            .define_value("FormatJustifyFill", QIcon::ThemeIcon::FormatJustifyFill)
            .define_value("FormatJustifyLeft", QIcon::ThemeIcon::FormatJustifyLeft)
            .define_value("FormatJustifyRight", QIcon::ThemeIcon::FormatJustifyRight)
            .define_value("FormatTextDirectionLtr", QIcon::ThemeIcon::FormatTextDirectionLtr)
            .define_value("FormatTextDirectionRtl", QIcon::ThemeIcon::FormatTextDirectionRtl)
            .define_value("FormatTextBold", QIcon::ThemeIcon::FormatTextBold)
            .define_value("FormatTextItalic", QIcon::ThemeIcon::FormatTextItalic)
            .define_value("FormatTextUnderline", QIcon::ThemeIcon::FormatTextUnderline)
            .define_value("FormatTextStrikethrough", QIcon::ThemeIcon::FormatTextStrikethrough)
            .define_value("GoDown", QIcon::ThemeIcon::GoDown)
            .define_value("GoHome", QIcon::ThemeIcon::GoHome)
            .define_value("GoNext", QIcon::ThemeIcon::GoNext)
            .define_value("GoPrevious", QIcon::ThemeIcon::GoPrevious)
            .define_value("GoUp", QIcon::ThemeIcon::GoUp)
            .define_value("HelpAbout", QIcon::ThemeIcon::HelpAbout)
            .define_value("HelpFaq", QIcon::ThemeIcon::HelpFaq)
            .define_value("InsertImage", QIcon::ThemeIcon::InsertImage)
            .define_value("InsertLink", QIcon::ThemeIcon::InsertLink)
            .define_value("InsertText", QIcon::ThemeIcon::InsertText)
            .define_value("ListAdd", QIcon::ThemeIcon::ListAdd)
            .define_value("ListRemove", QIcon::ThemeIcon::ListRemove)
            .define_value("MailForward", QIcon::ThemeIcon::MailForward)
            .define_value("MailMarkImportant", QIcon::ThemeIcon::MailMarkImportant)
            .define_value("MailMarkRead", QIcon::ThemeIcon::MailMarkRead)
            .define_value("MailMarkUnread", QIcon::ThemeIcon::MailMarkUnread)
            .define_value("MailMessageNew", QIcon::ThemeIcon::MailMessageNew)
            .define_value("MailReplyAll", QIcon::ThemeIcon::MailReplyAll)
            .define_value("MailReplySender", QIcon::ThemeIcon::MailReplySender)
            .define_value("MailSend", QIcon::ThemeIcon::MailSend)
            .define_value("MediaEject", QIcon::ThemeIcon::MediaEject)
            .define_value("MediaPlaybackPause", QIcon::ThemeIcon::MediaPlaybackPause)
            .define_value("MediaPlaybackStart", QIcon::ThemeIcon::MediaPlaybackStart)
            .define_value("MediaPlaybackStop", QIcon::ThemeIcon::MediaPlaybackStop)
            .define_value("MediaRecord", QIcon::ThemeIcon::MediaRecord)
            .define_value("MediaSeekBackward", QIcon::ThemeIcon::MediaSeekBackward)
            .define_value("MediaSeekForward", QIcon::ThemeIcon::MediaSeekForward)
            .define_value("MediaSkipBackward", QIcon::ThemeIcon::MediaSkipBackward)
            .define_value("MediaSkipForward", QIcon::ThemeIcon::MediaSkipForward)
            .define_value("ObjectRotateLeft", QIcon::ThemeIcon::ObjectRotateLeft)
            .define_value("ObjectRotateRight", QIcon::ThemeIcon::ObjectRotateRight)
            .define_value("ProcessStop", QIcon::ThemeIcon::ProcessStop)
            .define_value("SystemLockScreen", QIcon::ThemeIcon::SystemLockScreen)
            .define_value("SystemLogOut", QIcon::ThemeIcon::SystemLogOut)
            .define_value("SystemSearch", QIcon::ThemeIcon::SystemSearch)
            .define_value("SystemReboot", QIcon::ThemeIcon::SystemReboot)
            .define_value("SystemShutdown", QIcon::ThemeIcon::SystemShutdown)
            .define_value("ToolsCheckSpelling", QIcon::ThemeIcon::ToolsCheckSpelling)
            .define_value("ViewFullscreen", QIcon::ThemeIcon::ViewFullscreen)
            .define_value("ViewRefresh", QIcon::ThemeIcon::ViewRefresh)
            .define_value("ViewRestore", QIcon::ThemeIcon::ViewRestore)
            .define_value("WindowClose", QIcon::ThemeIcon::WindowClose)
            .define_value("WindowNew", QIcon::ThemeIcon::WindowNew)
            .define_value("ZoomFitBest", QIcon::ThemeIcon::ZoomFitBest)
            .define_value("ZoomIn", QIcon::ThemeIcon::ZoomIn)
            .define_value("ZoomOut", QIcon::ThemeIcon::ZoomOut)
            .define_value("AudioCard", QIcon::ThemeIcon::AudioCard)
            .define_value("AudioInputMicrophone", QIcon::ThemeIcon::AudioInputMicrophone)
            .define_value("Battery", QIcon::ThemeIcon::Battery)
            .define_value("CameraPhoto", QIcon::ThemeIcon::CameraPhoto)
            .define_value("CameraVideo", QIcon::ThemeIcon::CameraVideo)
            .define_value("CameraWeb", QIcon::ThemeIcon::CameraWeb)
            .define_value("Computer", QIcon::ThemeIcon::Computer)
            .define_value("DriveHarddisk", QIcon::ThemeIcon::DriveHarddisk)
            .define_value("DriveOptical", QIcon::ThemeIcon::DriveOptical)
            .define_value("InputGaming", QIcon::ThemeIcon::InputGaming)
            .define_value("InputKeyboard", QIcon::ThemeIcon::InputKeyboard)
            .define_value("InputMouse", QIcon::ThemeIcon::InputMouse)
            .define_value("InputTablet", QIcon::ThemeIcon::InputTablet)
            .define_value("MediaFlash", QIcon::ThemeIcon::MediaFlash)
            .define_value("MediaOptical", QIcon::ThemeIcon::MediaOptical)
            .define_value("MediaTape", QIcon::ThemeIcon::MediaTape)
            .define_value("MultimediaPlayer", QIcon::ThemeIcon::MultimediaPlayer)
            .define_value("NetworkWired", QIcon::ThemeIcon::NetworkWired)
            .define_value("NetworkWireless", QIcon::ThemeIcon::NetworkWireless)
            .define_value("Phone", QIcon::ThemeIcon::Phone)
            .define_value("Printer", QIcon::ThemeIcon::Printer)
            .define_value("Scanner", QIcon::ThemeIcon::Scanner)
            .define_value("VideoDisplay", QIcon::ThemeIcon::VideoDisplay)
            .define_value("AppointmentMissed", QIcon::ThemeIcon::AppointmentMissed)
            .define_value("AppointmentSoon", QIcon::ThemeIcon::AppointmentSoon)
            .define_value("AudioVolumeHigh", QIcon::ThemeIcon::AudioVolumeHigh)
            .define_value("AudioVolumeLow", QIcon::ThemeIcon::AudioVolumeLow)
            .define_value("AudioVolumeMedium", QIcon::ThemeIcon::AudioVolumeMedium)
            .define_value("AudioVolumeMuted", QIcon::ThemeIcon::AudioVolumeMuted)
            .define_value("BatteryCaution", QIcon::ThemeIcon::BatteryCaution)
            .define_value("BatteryLow", QIcon::ThemeIcon::BatteryLow)
            .define_value("DialogError", QIcon::ThemeIcon::DialogError)
            .define_value("DialogInformation", QIcon::ThemeIcon::DialogInformation)
            .define_value("DialogPassword", QIcon::ThemeIcon::DialogPassword)
            .define_value("DialogQuestion", QIcon::ThemeIcon::DialogQuestion)
            .define_value("DialogWarning", QIcon::ThemeIcon::DialogWarning)
            .define_value("FolderDragAccept", QIcon::ThemeIcon::FolderDragAccept)
            .define_value("FolderOpen", QIcon::ThemeIcon::FolderOpen)
            .define_value("FolderVisiting", QIcon::ThemeIcon::FolderVisiting)
            .define_value("ImageLoading", QIcon::ThemeIcon::ImageLoading)
            .define_value("ImageMissing", QIcon::ThemeIcon::ImageMissing)
            .define_value("MailAttachment", QIcon::ThemeIcon::MailAttachment)
            .define_value("MailUnread", QIcon::ThemeIcon::MailUnread)
            .define_value("MailRead", QIcon::ThemeIcon::MailRead)
            .define_value("MailReplied", QIcon::ThemeIcon::MailReplied)
            .define_value("MediaPlaylistRepeat", QIcon::ThemeIcon::MediaPlaylistRepeat)
            .define_value("MediaPlaylistShuffle", QIcon::ThemeIcon::MediaPlaylistShuffle)
            .define_value("NetworkOffline", QIcon::ThemeIcon::NetworkOffline)
            .define_value("PrinterPrinting", QIcon::ThemeIcon::PrinterPrinting)
            .define_value("SecurityHigh", QIcon::ThemeIcon::SecurityHigh)
            .define_value("SecurityLow", QIcon::ThemeIcon::SecurityLow)
            .define_value("SoftwareUpdateAvailable", QIcon::ThemeIcon::SoftwareUpdateAvailable)
            .define_value("SoftwareUpdateUrgent", QIcon::ThemeIcon::SoftwareUpdateUrgent)
            .define_value("SyncError", QIcon::ThemeIcon::SyncError)
            .define_value("SyncSynchronizing", QIcon::ThemeIcon::SyncSynchronizing)
            .define_value("UserAvailable", QIcon::ThemeIcon::UserAvailable)
            .define_value("UserOffline", QIcon::ThemeIcon::UserOffline)
            .define_value("WeatherClear", QIcon::ThemeIcon::WeatherClear)
            .define_value("WeatherClearNight", QIcon::ThemeIcon::WeatherClearNight)
            .define_value("WeatherFewClouds", QIcon::ThemeIcon::WeatherFewClouds)
            .define_value("WeatherFewCloudsNight", QIcon::ThemeIcon::WeatherFewCloudsNight)
            .define_value("WeatherFog", QIcon::ThemeIcon::WeatherFog)
            .define_value("WeatherShowers", QIcon::ThemeIcon::WeatherShowers)
            .define_value("WeatherSnow", QIcon::ThemeIcon::WeatherSnow)
            .define_value("WeatherStorm", QIcon::ThemeIcon::WeatherStorm)
            .define_value("NThemeIcons", QIcon::ThemeIcon::NThemeIcons);
}
