#include "qstandarditemmodel-rb.hpp"
#include <qstandarditemmodel.h>
#include <rice/qt6/qenum.hpp>

#include <QBindable>
#include <QMimeData>

RICE4RUBYQT6_USE_NAMESPACE

Class rb_cQStandardItemModel;
Class rb_cQStandardItem;

void Init_qstandarditemmodel(Module rb_mQt6QtGui)
{
    rb_cQStandardItemModel =
        // RubyQt6::QtGui::QStandardItemModel
        define_qlass_under<QStandardItemModel, QAbstractItemModel>(rb_mQt6QtGui, "QStandardItemModel")
            // RubyQt6-Defined Functions
            .define_singleton_function("_static_meta_object", []() -> const QMetaObject * { return &QStandardItemModel::staticMetaObject; })
            // Constructor
            .define_constructor(Constructor<QStandardItemModel, QObject *>(), Arg("parent"))
            // Public Functions
            .define_method("append_column", &QStandardItemModel::appendColumn, Arg("items"))
            .define_method<void (QStandardItemModel::*)(QStandardItem *)>("append_row", &QStandardItemModel::appendRow, Arg("item"))
            .define_method<void (QStandardItemModel::*)(const QList<QStandardItem *> &)>("append_row", &QStandardItemModel::appendRow, Arg("items"))
            .define_method("bindable_sort_role", &QStandardItemModel::bindableSortRole)
            .define_method("clear", &QStandardItemModel::clear)
            .define_method("clear_item_data", &QStandardItemModel::clearItemData, Arg("index"))
            .define_method("column_count", &QStandardItemModel::columnCount, Arg("parent") = static_cast<const QModelIndex &>(QModelIndex()))
            .define_method("data", &QStandardItemModel::data, Arg("index"), Arg("role") = static_cast<int>(Qt::DisplayRole))
            .define_method("drop_mime_data", &QStandardItemModel::dropMimeData, Arg("data"), Arg("action"), Arg("row"), Arg("column"), Arg("parent"))
            .define_method("find_items", &QStandardItemModel::findItems, Arg("text"), Arg("flags") = static_cast<Qt::MatchFlags>(Qt::MatchExactly), Arg("column") = static_cast<int>(0))
            .define_method("flags", &QStandardItemModel::flags, Arg("index"))
            .define_method("has_children", &QStandardItemModel::hasChildren, Arg("parent") = static_cast<const QModelIndex &>(QModelIndex()))
            .define_method("header_data", &QStandardItemModel::headerData, Arg("section"), Arg("orientation"), Arg("role") = static_cast<int>(Qt::DisplayRole))
            .define_method("horizontal_header_item", &QStandardItemModel::horizontalHeaderItem, Arg("column"))
            .define_method("index", &QStandardItemModel::index, Arg("row"), Arg("column"), Arg("parent") = static_cast<const QModelIndex &>(QModelIndex()))
            .define_method("index_from_item", &QStandardItemModel::indexFromItem, Arg("item"))
            .define_method<bool (QStandardItemModel::*)(int, const QModelIndex &)>("insert_column", &QStandardItemModel::insertColumn, Arg("column"), Arg("parent") = static_cast<const QModelIndex &>(QModelIndex()))
            .define_method<void (QStandardItemModel::*)(int, const QList<QStandardItem *> &)>("insert_column", &QStandardItemModel::insertColumn, Arg("column"), Arg("items"))
            .define_method("insert_columns", &QStandardItemModel::insertColumns, Arg("column"), Arg("count"), Arg("parent") = static_cast<const QModelIndex &>(QModelIndex()))
            .define_method<bool (QStandardItemModel::*)(int, const QModelIndex &)>("insert_row", &QStandardItemModel::insertRow, Arg("row"), Arg("parent") = static_cast<const QModelIndex &>(QModelIndex()))
            .define_method<void (QStandardItemModel::*)(int, QStandardItem *)>("insert_row", &QStandardItemModel::insertRow, Arg("row"), Arg("item"))
            .define_method<void (QStandardItemModel::*)(int, const QList<QStandardItem *> &)>("insert_row", &QStandardItemModel::insertRow, Arg("row"), Arg("items"))
            .define_method("insert_rows", &QStandardItemModel::insertRows, Arg("row"), Arg("count"), Arg("parent") = static_cast<const QModelIndex &>(QModelIndex()))
            .define_method("invisible_root_item", &QStandardItemModel::invisibleRootItem)
            .define_method("item", &QStandardItemModel::item, Arg("row"), Arg("column") = static_cast<int>(0))
            .define_method("item_data", &QStandardItemModel::itemData, Arg("index"))
            .define_method("item_from_index", &QStandardItemModel::itemFromIndex, Arg("index"))
            .define_method("item_prototype", &QStandardItemModel::itemPrototype)
            .define_method("mime_data", &QStandardItemModel::mimeData, Arg("indexes"))
            .define_method("mime_types", &QStandardItemModel::mimeTypes)
            .define_method("multi_data", &QStandardItemModel::multiData, Arg("index"), Arg("role_data_span"))
            // .define_method("parent", &QStandardItemModel::parent, Arg("child"))
            .define_method("remove_columns", &QStandardItemModel::removeColumns, Arg("column"), Arg("count"), Arg("parent") = static_cast<const QModelIndex &>(QModelIndex()))
            .define_method("remove_rows", &QStandardItemModel::removeRows, Arg("row"), Arg("count"), Arg("parent") = static_cast<const QModelIndex &>(QModelIndex()))
            .define_method("role_names", &QStandardItemModel::roleNames)
            .define_method("row_count", &QStandardItemModel::rowCount, Arg("parent") = static_cast<const QModelIndex &>(QModelIndex()))
            .define_method("set_column_count", &QStandardItemModel::setColumnCount, Arg("columns"))
            .define_method("set_data", &QStandardItemModel::setData, Arg("index"), Arg("value"), Arg("role") = static_cast<int>(Qt::EditRole))
            .define_method("set_header_data", &QStandardItemModel::setHeaderData, Arg("section"), Arg("orientation"), Arg("value"), Arg("role") = static_cast<int>(Qt::EditRole))
            .define_method("set_horizontal_header_item", &QStandardItemModel::setHorizontalHeaderItem, Arg("column"), Arg("item"))
            .define_method("set_horizontal_header_labels", &QStandardItemModel::setHorizontalHeaderLabels, Arg("labels"))
            .define_method<void (QStandardItemModel::*)(int, QStandardItem *)>("set_item", &QStandardItemModel::setItem, Arg("row"), Arg("item"))
            .define_method<void (QStandardItemModel::*)(int, int, QStandardItem *)>("set_item", &QStandardItemModel::setItem, Arg("row"), Arg("column"), Arg("item"))
            .define_method("set_item_data", &QStandardItemModel::setItemData, Arg("index"), Arg("roles"))
            .define_method("set_item_prototype", &QStandardItemModel::setItemPrototype, Arg("item"))
            .define_method("set_item_role_names", &QStandardItemModel::setItemRoleNames, Arg("role_names"))
            .define_method("set_row_count", &QStandardItemModel::setRowCount, Arg("rows"))
            .define_method("set_sort_role", &QStandardItemModel::setSortRole, Arg("role"))
            .define_method("set_vertical_header_item", &QStandardItemModel::setVerticalHeaderItem, Arg("row"), Arg("item"))
            .define_method("set_vertical_header_labels", &QStandardItemModel::setVerticalHeaderLabels, Arg("labels"))
            .define_method("sort", &QStandardItemModel::sort, Arg("column"), Arg("order") = static_cast<Qt::SortOrder>(Qt::AscendingOrder))
            .define_method("sort_role", &QStandardItemModel::sortRole)
            .define_method("supported_drop_actions", &QStandardItemModel::supportedDropActions)
            .define_method("take_column", &QStandardItemModel::takeColumn, Arg("column"))
            .define_method("take_horizontal_header_item", &QStandardItemModel::takeHorizontalHeaderItem, Arg("column"))
            .define_method("take_item", &QStandardItemModel::takeItem, Arg("row"), Arg("column") = static_cast<int>(0))
            .define_method("take_row", &QStandardItemModel::takeRow, Arg("row"))
            .define_method("take_vertical_header_item", &QStandardItemModel::takeVerticalHeaderItem, Arg("row"))
            .define_method("vertical_header_item", &QStandardItemModel::verticalHeaderItem, Arg("row"));
            // Signals
            // .define_method("item_changed", &QStandardItemModel::itemChanged, Arg("item"));

    rb_cQStandardItem =
        // RubyQt6::QtGui::QStandardItem
        define_qlass_under<QStandardItem>(rb_mQt6QtGui, "QStandardItem")
            // RubyQt6-Defined Functions
            .define_singleton_function("_qvariant_register_metatype", []() -> int { return qRegisterMetaType<QStandardItem *>(); })
            .define_singleton_function("_qvariant_from_value", [](QStandardItem *value) -> QVariant { return QVariant::fromValue(value); })
            .define_singleton_function("_qvariant_to_value", [](const QVariant &qvariant) -> QStandardItem * { return qvariant.value<QStandardItem *>(); })
            .define_singleton_function("_delete_now", [](QStandardItem *item) -> void { delete item; }, Arg("item").takeOwnership())
            .define_singleton_function("_take_ownership_from_ruby", [](QStandardItem *) -> void {}, Arg("item").takeOwnership())
            // Constructor
            .define_constructor(Constructor<QStandardItem>())
            .define_constructor(Constructor<QStandardItem, const QString &>(), Arg("text"))
            .define_constructor(Constructor<QStandardItem, const QIcon &, const QString &>(), Arg("icon"), Arg("text"))
            .define_constructor(Constructor<QStandardItem, int, int>(), Arg("rows"), Arg("columns"))
            // Public Functions
            .define_method("accessible_description", &QStandardItem::accessibleDescription)
            .define_method("accessible_text", &QStandardItem::accessibleText)
            .define_method("append_column", &QStandardItem::appendColumn, Arg("items"))
            .define_method<void (QStandardItem::*)(QStandardItem *)>("append_row", &QStandardItem::appendRow, Arg("item"))
            .define_method<void (QStandardItem::*)(const QList<QStandardItem *> &)>("append_row", &QStandardItem::appendRow, Arg("items"))
            .define_method("append_rows", &QStandardItem::appendRows, Arg("items"))
            .define_method("background", &QStandardItem::background)
            .define_method("check_state", &QStandardItem::checkState)
            .define_method("child", &QStandardItem::child, Arg("row"), Arg("column") = static_cast<int>(0))
            .define_method("clear_data", &QStandardItem::clearData)
            .define_method("column", &QStandardItem::column)
            .define_method("column_count", &QStandardItem::columnCount)
            .define_method("data", &QStandardItem::data, Arg("role") = static_cast<int>(Qt::UserRole + 1))
            .define_method("flags", &QStandardItem::flags)
            .define_method("font", &QStandardItem::font)
            .define_method("foreground", &QStandardItem::foreground)
            .define_method("has_children", &QStandardItem::hasChildren)
            .define_method("icon", &QStandardItem::icon)
            .define_method("index", &QStandardItem::index)
            .define_method("insert_column", &QStandardItem::insertColumn, Arg("column"), Arg("items"))
            .define_method("insert_columns", &QStandardItem::insertColumns, Arg("column"), Arg("count"))
            .define_method<void (QStandardItem::*)(int, QStandardItem *)>("insert_row", &QStandardItem::insertRow, Arg("row"), Arg("item"))
            .define_method<void (QStandardItem::*)(int, const QList<QStandardItem *> &)>("insert_row", &QStandardItem::insertRow, Arg("row"), Arg("items"))
            .define_method<void (QStandardItem::*)(int, const QList<QStandardItem *> &)>("insert_rows", &QStandardItem::insertRows, Arg("row"), Arg("items"))
            .define_method<void (QStandardItem::*)(int, int)>("insert_rows", &QStandardItem::insertRows, Arg("row"), Arg("count"))
            .define_method("auto_tristate?", &QStandardItem::isAutoTristate)
            .define_method("checkable?", &QStandardItem::isCheckable)
            .define_method("drag_enabled?", &QStandardItem::isDragEnabled)
            .define_method("drop_enabled?", &QStandardItem::isDropEnabled)
            .define_method("editable?", &QStandardItem::isEditable)
            .define_method("enabled?", &QStandardItem::isEnabled)
            .define_method("selectable?", &QStandardItem::isSelectable)
            .define_method("user_tristate?", &QStandardItem::isUserTristate)
            .define_method("model", &QStandardItem::model)
            .define_method("multi_data", &QStandardItem::multiData, Arg("role_data_span"))
            .define_method("parent", &QStandardItem::parent)
            .define_method("read", &QStandardItem::read, Arg("in"))
            .define_method("remove_column", &QStandardItem::removeColumn, Arg("column"))
            .define_method("remove_columns", &QStandardItem::removeColumns, Arg("column"), Arg("count"))
            .define_method("remove_row", &QStandardItem::removeRow, Arg("row"))
            .define_method("remove_rows", &QStandardItem::removeRows, Arg("row"), Arg("count"))
            .define_method("row", &QStandardItem::row)
            .define_method("row_count", &QStandardItem::rowCount)
            .define_method("set_accessible_description", &QStandardItem::setAccessibleDescription, Arg("accessible_description"))
            .define_method("set_accessible_text", &QStandardItem::setAccessibleText, Arg("accessible_text"))
            .define_method("set_auto_tristate", &QStandardItem::setAutoTristate, Arg("tristate"))
            .define_method("set_background", &QStandardItem::setBackground, Arg("brush"))
            .define_method("set_check_state", &QStandardItem::setCheckState, Arg("check_state"))
            .define_method("set_checkable", &QStandardItem::setCheckable, Arg("checkable"))
            .define_method<void (QStandardItem::*)(int, QStandardItem *)>("set_child", &QStandardItem::setChild, Arg("row"), Arg("item"))
            .define_method<void (QStandardItem::*)(int, int, QStandardItem *)>("set_child", &QStandardItem::setChild, Arg("row"), Arg("column"), Arg("item"))
            .define_method("set_column_count", &QStandardItem::setColumnCount, Arg("columns"))
            .define_method("set_data", &QStandardItem::setData, Arg("value"), Arg("role") = static_cast<int>(Qt::UserRole + 1))
            .define_method("set_drag_enabled", &QStandardItem::setDragEnabled, Arg("drag_enabled"))
            .define_method("set_drop_enabled", &QStandardItem::setDropEnabled, Arg("drop_enabled"))
            .define_method("set_editable", &QStandardItem::setEditable, Arg("editable"))
            .define_method("set_enabled", &QStandardItem::setEnabled, Arg("enabled"))
            .define_method("set_flags", &QStandardItem::setFlags, Arg("flags"))
            .define_method("set_font", &QStandardItem::setFont, Arg("font"))
            .define_method("set_foreground", &QStandardItem::setForeground, Arg("brush"))
            .define_method("set_icon", &QStandardItem::setIcon, Arg("icon"))
            .define_method("set_row_count", &QStandardItem::setRowCount, Arg("rows"))
            .define_method("set_selectable", &QStandardItem::setSelectable, Arg("selectable"))
            .define_method("set_size_hint", &QStandardItem::setSizeHint, Arg("size_hint"))
            .define_method("set_status_tip", &QStandardItem::setStatusTip, Arg("status_tip"))
            .define_method("set_text", &QStandardItem::setText, Arg("text"))
            .define_method("set_text_alignment", &QStandardItem::setTextAlignment, Arg("text_alignment"))
            .define_method("set_tool_tip", &QStandardItem::setToolTip, Arg("tool_tip"))
            .define_method("set_user_tristate", &QStandardItem::setUserTristate, Arg("tristate"))
            .define_method("set_whats_this", &QStandardItem::setWhatsThis, Arg("whats_this"))
            .define_method("sort_children", &QStandardItem::sortChildren, Arg("column"), Arg("order") = static_cast<Qt::SortOrder>(Qt::AscendingOrder))
            .define_method("status_tip", &QStandardItem::statusTip)
            .define_method("take_child", &QStandardItem::takeChild, Arg("row"), Arg("column") = static_cast<int>(0))
            .define_method("take_column", &QStandardItem::takeColumn, Arg("column"))
            .define_method("take_row", &QStandardItem::takeRow, Arg("row"))
            .define_method("text", &QStandardItem::text)
            .define_method("text_alignment", &QStandardItem::textAlignment)
            .define_method("tool_tip", &QStandardItem::toolTip)
            .define_method("type", &QStandardItem::type)
            .define_method("whats_this", &QStandardItem::whatsThis)
            .define_method("write", &QStandardItem::write, Arg("out"));

    Data_Type<QStandardItem::ItemType> rb_cQStandardItemItemType =
        // RubyQt6::QtGui::QStandardItem::ItemType
        define_qenum_under<QStandardItem::ItemType>(rb_cQStandardItem, "ItemType");
        define_qenum_value_under(rb_cQStandardItemItemType, "Type", QStandardItem::ItemType::Type);
        define_qenum_value_under(rb_cQStandardItemItemType, "UserType", QStandardItem::ItemType::UserType);
}
