#include "qquickitem-rb.hpp"
#include <qquickitem.h>

#include <QQuickWindow>
#include <QSGTextureProvider>

using namespace Rice;

Rice::Class rb_cQQuickItem;

void Init_qquickitem(Rice::Module rb_mQt6QtQuick)
{
    rb_cQQuickItem =
        // RubyQt6::QtQuick::QQuickItem
        define_class_under<QQuickItem, QObject>(rb_mQt6QtQuick, "QQuickItem")
            // RubyQt6-Defined Functions
            .define_singleton_function("_static_meta_object", []() -> const QMetaObject * { return &QQuickItem::staticMetaObject; })
            // Constructor
            .define_constructor(Constructor<QQuickItem, QQuickItem *>(), Arg("parent") = static_cast<QQuickItem *>(nullptr))
            // inherits QQmlParserStatus
            // .define_method("class_begin", &QQuickItem::classBegin)
            // .define_method("component_complete", &QQuickItem::componentComplete)
            // Public Functions
            .define_method("accept_hover_events", &QQuickItem::acceptHoverEvents)
            .define_method("accept_touch_events", &QQuickItem::acceptTouchEvents)
            .define_method("accepted_mouse_buttons", &QQuickItem::acceptedMouseButtons)
            .define_method("active_focus_on_tab", &QQuickItem::activeFocusOnTab)
            .define_method("antialiasing", &QQuickItem::antialiasing)
            .define_method("baseline_offset", &QQuickItem::baselineOffset)
            .define_method("bindable_height", &QQuickItem::bindableHeight)
            .define_method("bindable_width", &QQuickItem::bindableWidth)
            .define_method("bindable_x", &QQuickItem::bindableX)
            .define_method("bindable_y", &QQuickItem::bindableY)
            .define_method("bounding_rect", &QQuickItem::boundingRect)
            .define_method("child_at", &QQuickItem::childAt, Arg("x"), Arg("y"))
            .define_method("child_items", &QQuickItem::childItems)
            .define_method("children_rect", &QQuickItem::childrenRect)
            .define_method("clip", &QQuickItem::clip)
            .define_method("clip_rect", &QQuickItem::clipRect)
            .define_method("containment_mask", &QQuickItem::containmentMask)
            .define_method("contains", &QQuickItem::contains, Arg("point"))
            .define_method("cursor", &QQuickItem::cursor)
            .define_method("dump_item_tree", &QQuickItem::dumpItemTree)
            .define_method("ensure_polished", &QQuickItem::ensurePolished)
            .define_method("filters_child_mouse_events", &QQuickItem::filtersChildMouseEvents)
            .define_method("flags", &QQuickItem::flags)
            .define_method("focus_policy", &QQuickItem::focusPolicy)
            .define_method<void (QQuickItem::*)()>("force_active_focus", &QQuickItem::forceActiveFocus)
            .define_method<void (QQuickItem::*)(Qt::FocusReason)>("force_active_focus", &QQuickItem::forceActiveFocus, Arg("reason"))
            .define_method("grab_mouse", &QQuickItem::grabMouse)
            // .define_method<QSharedPointer (QQuickItem::*)(const QSize &)>("grab_to_image", &QQuickItem::grabToImage, Arg("target_size") = static_cast<const QSize &>(QSize()))
            // .define_method<bool (QQuickItem::*)(const QJSValue &, const QSize &)>("grab_to_image", &QQuickItem::grabToImage, Arg("callback"), Arg("target_size") = static_cast<const QSize &>(QSize()))
            .define_method("grab_touch_points", &QQuickItem::grabTouchPoints, Arg("ids"))
            .define_method("has_active_focus", &QQuickItem::hasActiveFocus)
            .define_method("has_focus", &QQuickItem::hasFocus)
            .define_method("height", &QQuickItem::height)
            .define_method("implicit_height", &QQuickItem::implicitHeight)
            .define_method("implicit_width", &QQuickItem::implicitWidth)
            .define_method("input_method_query", &QQuickItem::inputMethodQuery, Arg("query"))
            .define_method("ancestor_of?", &QQuickItem::isAncestorOf, Arg("child"))
            .define_method("enabled?", &QQuickItem::isEnabled)
            .define_method("focus_scope?", &QQuickItem::isFocusScope)
            .define_method("texture_provider?", &QQuickItem::isTextureProvider)
            .define_method("under_mouse?", &QQuickItem::isUnderMouse)
            .define_method("visible?", &QQuickItem::isVisible)
            .define_method("item_transform", &QQuickItem::itemTransform, Arg(""), Arg(""))
            .define_method("keep_mouse_grab", &QQuickItem::keepMouseGrab)
            .define_method("keep_touch_grab", &QQuickItem::keepTouchGrab)
            .define_method<QPointF (QQuickItem::*)(const QPointF &) const>("map_from_global", &QQuickItem::mapFromGlobal, Arg("point"))
            .define_method<QPointF (QQuickItem::*)(qreal, qreal) const>("map_from_global", &QQuickItem::mapFromGlobal, Arg("x"), Arg("y"))
            .define_method<QPointF (QQuickItem::*)(const QQuickItem *, const QPointF &) const>("map_from_item", &QQuickItem::mapFromItem, Arg("item"), Arg("point"))
            .define_method<QPointF (QQuickItem::*)(const QQuickItem *, qreal, qreal)>("map_from_item", &QQuickItem::mapFromItem, Arg("item"), Arg("x"), Arg("y"))
            .define_method<QRectF (QQuickItem::*)(const QQuickItem *, const QRectF &) const>("map_from_item", &QQuickItem::mapFromItem, Arg("item"), Arg("rect"))
            .define_method<QRectF (QQuickItem::*)(const QQuickItem *, qreal, qreal, qreal, qreal) const>("map_from_item", &QQuickItem::mapFromItem, Arg("item"), Arg("x"), Arg("y"), Arg("width"), Arg("height"))
            .define_method("map_from_scene", &QQuickItem::mapFromScene, Arg("point"))
            .define_method("map_rect_from_item", &QQuickItem::mapRectFromItem, Arg("item"), Arg("rect"))
            .define_method("map_rect_from_scene", &QQuickItem::mapRectFromScene, Arg("rect"))
            .define_method("map_rect_to_item", &QQuickItem::mapRectToItem, Arg("item"), Arg("rect"))
            .define_method("map_rect_to_scene", &QQuickItem::mapRectToScene, Arg("rect"))
            .define_method<QPointF (QQuickItem::*)(const QPointF &) const>("map_to_global", &QQuickItem::mapToGlobal, Arg("point"))
            .define_method<QPointF (QQuickItem::*)(qreal, qreal) const>("map_to_global", &QQuickItem::mapToGlobal, Arg("x"), Arg("y"))
            .define_method<QPointF (QQuickItem::*)(const QQuickItem *, const QPointF &) const>("map_to_item", &QQuickItem::mapToItem, Arg("item"), Arg("point"))
            .define_method<QPointF (QQuickItem::*)(const QQuickItem *, qreal, qreal)>("map_to_item", &QQuickItem::mapToItem, Arg("item"), Arg("x"), Arg("y"))
            .define_method<QRectF (QQuickItem::*)(const QQuickItem *, const QRectF &) const>("map_to_item", &QQuickItem::mapToItem, Arg("item"), Arg("rect"))
            .define_method<QRectF (QQuickItem::*)(const QQuickItem *, qreal, qreal, qreal, qreal) const>("map_to_item", &QQuickItem::mapToItem, Arg("item"), Arg("x"), Arg("y"), Arg("width"), Arg("height"))
            .define_method("map_to_scene", &QQuickItem::mapToScene, Arg("point"))
            .define_method("next_item_in_focus_chain", &QQuickItem::nextItemInFocusChain, Arg("forward") = static_cast<bool>(true))
            .define_method("opacity", &QQuickItem::opacity)
            .define_method("parent_item", &QQuickItem::parentItem)
            .define_method("polish", &QQuickItem::polish)
            .define_method("position", &QQuickItem::position)
            .define_method("reset_antialiasing", &QQuickItem::resetAntialiasing)
            .define_method("reset_height", &QQuickItem::resetHeight)
            .define_method("reset_width", &QQuickItem::resetWidth)
            .define_method("rotation", &QQuickItem::rotation)
            .define_method("scale", &QQuickItem::scale)
            .define_method("scoped_focus_item", &QQuickItem::scopedFocusItem)
            .define_method("set_accept_hover_events", &QQuickItem::setAcceptHoverEvents, Arg("enabled"))
            .define_method("set_accept_touch_events", &QQuickItem::setAcceptTouchEvents, Arg("accept"))
            .define_method("set_accepted_mouse_buttons", &QQuickItem::setAcceptedMouseButtons, Arg("buttons"))
            .define_method("set_active_focus_on_tab", &QQuickItem::setActiveFocusOnTab, Arg(""))
            .define_method("set_antialiasing", &QQuickItem::setAntialiasing, Arg(""))
            .define_method("set_baseline_offset", &QQuickItem::setBaselineOffset, Arg(""))
            .define_method("set_clip", &QQuickItem::setClip, Arg(""))
            .define_method("set_containment_mask", &QQuickItem::setContainmentMask, Arg("mask"))
            .define_method("set_cursor", &QQuickItem::setCursor, Arg("cursor"))
            .define_method("set_enabled", &QQuickItem::setEnabled, Arg(""))
            .define_method("set_filters_child_mouse_events", &QQuickItem::setFiltersChildMouseEvents, Arg("filter"))
            .define_method("set_flag", &QQuickItem::setFlag, Arg("flag"), Arg("enabled") = static_cast<bool>(true))
            .define_method("set_flags", &QQuickItem::setFlags, Arg("flags"))
            .define_method<void (QQuickItem::*)(bool)>("set_focus", &QQuickItem::setFocus, Arg(""))
            .define_method<void (QQuickItem::*)(bool, Qt::FocusReason)>("set_focus", &QQuickItem::setFocus, Arg("focus"), Arg("reason"))
            .define_method("set_focus_policy", &QQuickItem::setFocusPolicy, Arg("policy"))
            .define_method("set_height", &QQuickItem::setHeight, Arg(""))
            .define_method("set_implicit_height", &QQuickItem::setImplicitHeight, Arg(""))
            .define_method("set_implicit_width", &QQuickItem::setImplicitWidth, Arg(""))
            .define_method("set_keep_mouse_grab", &QQuickItem::setKeepMouseGrab, Arg(""))
            .define_method("set_keep_touch_grab", &QQuickItem::setKeepTouchGrab, Arg(""))
            .define_method("set_opacity", &QQuickItem::setOpacity, Arg(""))
            .define_method("_set_parent_item", &QQuickItem::setParentItem, Arg("parent"))
            .define_method("set_position", &QQuickItem::setPosition, Arg(""))
            .define_method("set_rotation", &QQuickItem::setRotation, Arg(""))
            .define_method("set_scale", &QQuickItem::setScale, Arg(""))
            .define_method("set_size", &QQuickItem::setSize, Arg("size"))
            .define_method("set_smooth", &QQuickItem::setSmooth, Arg(""))
            .define_method("set_state", &QQuickItem::setState, Arg(""))
            .define_method("set_transform_origin", &QQuickItem::setTransformOrigin, Arg(""))
            .define_method("set_transform_origin_point", &QQuickItem::setTransformOriginPoint, Arg(""))
            .define_method("set_visible", &QQuickItem::setVisible, Arg(""))
            .define_method("set_width", &QQuickItem::setWidth, Arg(""))
            .define_method("set_x", &QQuickItem::setX, Arg(""))
            .define_method("set_y", &QQuickItem::setY, Arg(""))
            .define_method("set_z", &QQuickItem::setZ, Arg(""))
            .define_method("size", &QQuickItem::size)
            .define_method("smooth", &QQuickItem::smooth)
            .define_method("stack_after", &QQuickItem::stackAfter, Arg(""))
            .define_method("stack_before", &QQuickItem::stackBefore, Arg(""))
            .define_method("state", &QQuickItem::state)
            .define_method("texture_provider", &QQuickItem::textureProvider)
            .define_method("transform", &QQuickItem::transform)
            .define_method("transform_origin", &QQuickItem::transformOrigin)
            .define_method("transform_origin_point", &QQuickItem::transformOriginPoint)
            .define_method("ungrab_mouse", &QQuickItem::ungrabMouse)
            .define_method("ungrab_touch_points", &QQuickItem::ungrabTouchPoints)
            .define_method("unset_cursor", &QQuickItem::unsetCursor)
            .define_method("viewport_item", &QQuickItem::viewportItem)
            .define_method("width", &QQuickItem::width)
            .define_method("window", &QQuickItem::window)
            .define_method("x", &QQuickItem::x)
            .define_method("y", &QQuickItem::y)
            .define_method("z", &QQuickItem::z)
            // Public Slots
            .define_method("update", &QQuickItem::update)
            // Signals
            .define_method("active_focus_changed", &QQuickItem::activeFocusChanged, Arg(""))
            .define_method("active_focus_on_tab_changed", &QQuickItem::activeFocusOnTabChanged, Arg(""))
            .define_method("antialiasing_changed", &QQuickItem::antialiasingChanged, Arg(""))
            .define_method("baseline_offset_changed", &QQuickItem::baselineOffsetChanged, Arg(""))
            .define_method("children_changed", &QQuickItem::childrenChanged)
            .define_method("children_rect_changed", &QQuickItem::childrenRectChanged, Arg(""))
            .define_method("clip_changed", &QQuickItem::clipChanged, Arg(""))
            .define_method("containment_mask_changed", &QQuickItem::containmentMaskChanged)
            .define_method("enabled_changed", &QQuickItem::enabledChanged)
            .define_method("focus_changed", &QQuickItem::focusChanged, Arg(""))
            .define_method("focus_policy_changed", &QQuickItem::focusPolicyChanged, Arg(""))
            .define_method("height_changed", &QQuickItem::heightChanged)
            .define_method("implicit_height_changed", &QQuickItem::implicitHeightChanged)
            .define_method("implicit_width_changed", &QQuickItem::implicitWidthChanged)
            .define_method("opacity_changed", &QQuickItem::opacityChanged)
            .define_method("parent_changed", &QQuickItem::parentChanged, Arg(""))
            .define_method("rotation_changed", &QQuickItem::rotationChanged)
            .define_method("scale_changed", &QQuickItem::scaleChanged)
            .define_method("smooth_changed", &QQuickItem::smoothChanged, Arg(""))
            .define_method("state_changed", &QQuickItem::stateChanged, Arg(""))
            .define_method("transform_origin_changed", &QQuickItem::transformOriginChanged, Arg(""))
            .define_method("visible_changed", &QQuickItem::visibleChanged)
            .define_method("visible_children_changed", &QQuickItem::visibleChildrenChanged)
            .define_method("width_changed", &QQuickItem::widthChanged)
            .define_method("window_changed", &QQuickItem::windowChanged, Arg("window"))
            .define_method("x_changed", &QQuickItem::xChanged)
            .define_method("y_changed", &QQuickItem::yChanged)
            .define_method("z_changed", &QQuickItem::zChanged);
}
