# frozen_string_literal: true

require "qt6/qtcore"
require "qt6/qtgui"
require "qt6/qtwidgets"
require "qt6/qtdbus"
require "qt6/qtnetwork"
require "qt6/qtprintsupport"
require "qt6/qttest"
require "qt6/qtqml"
require "qt6/qtquick"
require "qt6/qtquickcontrols2"
require "qt6/qtquickwidgets"
require "qt6/qtmultimedia"
require "qt6/qtmultimediawidgets"
require "qt6/qtwebenginecore"
require "qt6/qtwebenginewidgets"
require "qt6/qtwebview"
require "qt6/qtuitools"
