# frozen_string_literal: true

source "https://rubygems.org"

# Specify your gem's dependencies in kguiaddons.gemspec
gemspec

# ruby-qt6
%w[rspec rice qtcore qtgui kcoreaddons].each do |lib|
  gem "ruby-qt6-#{lib}", path: "../#{lib}"
end

# rake
gem "irb"
gem "rake", "~> 13.0"
gem "rake-compiler"

# lint
gem "rubocop"
gem "standard"

# test
gem "rspec"

# doc
gem "yard"
gem "redcarpet"

# lsp
gem "solargraph"
