#include "kmessagebox-rb.hpp"
#include <kmessagebox.h>
#include <rice/qt6/qenum.hpp>
#include <rice/qt6/qflags.hpp>

RICE4RUBYQT6_USE_NAMESPACE

void Init_kmessagebox(Module rb_mQt6KWidgetsAddons)
{
    Module rb_mKMessageBox =
        // RubyQt6::KWidgetsAddons::KMessageBox
        define_module_under(rb_mQt6KWidgetsAddons, "KMessageBox");

    Data_Type<KMessageBox::ButtonCode> rb_cKMessageBoxButtonCode =
        // RubyQt6::KWidgetsAddons::KMessageBox::ButtonCode
        define_qenum_under<KMessageBox::ButtonCode>(rb_mKMessageBox, "ButtonCode");
        define_qenum_value_under(rb_cKMessageBoxButtonCode, "Ok", KMessageBox::ButtonCode::Ok);
        define_qenum_value_under(rb_cKMessageBoxButtonCode, "Cancel", KMessageBox::ButtonCode::Cancel);
        define_qenum_value_under(rb_cKMessageBoxButtonCode, "PrimaryAction", KMessageBox::ButtonCode::PrimaryAction);
        define_qenum_value_under(rb_cKMessageBoxButtonCode, "SecondaryAction", KMessageBox::ButtonCode::SecondaryAction);
        define_qenum_value_under(rb_cKMessageBoxButtonCode, "Continue", KMessageBox::ButtonCode::Continue);

    Data_Type<KMessageBox::DialogType> rb_cKMessageBoxDialogType =
        // RubyQt6::KWidgetsAddons::KMessageBox::DialogType
        define_qenum_under<KMessageBox::DialogType>(rb_mKMessageBox, "DialogType");
        define_qenum_value_under(rb_cKMessageBoxDialogType, "QuestionTwoActions", KMessageBox::DialogType::QuestionTwoActions);
        define_qenum_value_under(rb_cKMessageBoxDialogType, "WarningTwoActions", KMessageBox::DialogType::WarningTwoActions);
        define_qenum_value_under(rb_cKMessageBoxDialogType, "WarningContinueCancel", KMessageBox::DialogType::WarningContinueCancel);
        define_qenum_value_under(rb_cKMessageBoxDialogType, "WarningTwoActionsCancel", KMessageBox::DialogType::WarningTwoActionsCancel);
        define_qenum_value_under(rb_cKMessageBoxDialogType, "Information", KMessageBox::DialogType::Information);
        define_qenum_value_under(rb_cKMessageBoxDialogType, "Error", KMessageBox::DialogType::Error);
        define_qenum_value_under(rb_cKMessageBoxDialogType, "QuestionTwoActionsCancel", KMessageBox::DialogType::QuestionTwoActionsCancel);

    Data_Type<KMessageBox::Option> rb_cKMessageBoxOption =
        // RubyQt6::KWidgetsAddons::KMessageBox::Option
        define_qenum_under<KMessageBox::Option>(rb_mKMessageBox, "Option");
        define_qenum_value_under(rb_cKMessageBoxOption, "Notify", KMessageBox::Option::Notify);
        define_qenum_value_under(rb_cKMessageBoxOption, "AllowLink", KMessageBox::Option::AllowLink);
        define_qenum_value_under(rb_cKMessageBoxOption, "Dangerous", KMessageBox::Option::Dangerous);
        define_qenum_value_under(rb_cKMessageBoxOption, "NoExec", KMessageBox::Option::NoExec);
        define_qenum_value_under(rb_cKMessageBoxOption, "WindowModal", KMessageBox::Option::WindowModal);
        define_qenum_value_under(rb_cKMessageBoxOption, "PlainText", KMessageBox::Option::PlainText);

    Data_Type<QFlags<KMessageBox::Option>> rb_cKMessageBoxOptions =
        // RubyQt6::KWidgetsAddons::KMessageBox::Options
        define_qflags_under<KMessageBox::Option>(rb_mKMessageBox, "Options");

    rb_mKMessageBox.define_module_function("question_two_actions", &KMessageBox::questionTwoActions, Arg("parent"), Arg("text"), Arg("title"), Arg("primary_action"), Arg("secondary_action"), Arg("dont_ask_again_name") = static_cast<const QString &>(QString()), Arg("options") = static_cast<KMessageBox::Options>(KMessageBox::Notify));
    rb_mKMessageBox.define_module_function("question_two_actions_cancel", &KMessageBox::questionTwoActionsCancel, Arg("parent"), Arg("text"), Arg("title"), Arg("primary_action"), Arg("secondary_action"), Arg("cancel_action") = static_cast<const KGuiItem &>(KStandardGuiItem::cancel()), Arg("dont_ask_again_name") = static_cast<const QString &>(QString()), Arg("options") = static_cast<KMessageBox::Options>(KMessageBox::Notify));
    rb_mKMessageBox.define_module_function("question_two_actions_list", &KMessageBox::questionTwoActionsList, Arg("parent"), Arg("text"), Arg("strlist"), Arg("title"), Arg("primary_action"), Arg("secondary_action"), Arg("dont_ask_again_name") = static_cast<const QString &>(QString()), Arg("options") = static_cast<KMessageBox::Options>(KMessageBox::Notify));
    rb_mKMessageBox.define_module_function("warning_two_actions", &KMessageBox::warningTwoActions, Arg("parent"), Arg("text"), Arg("title"), Arg("primary_action"), Arg("secondary_action"), Arg("dont_ask_again_name") = static_cast<const QString &>(QString()), Arg("options") = static_cast<KMessageBox::Options>(KMessageBox::Options(KMessageBox::Notify | KMessageBox::Dangerous)));
    rb_mKMessageBox.define_module_function("warning_two_actions_list", &KMessageBox::warningTwoActionsList, Arg("parent"), Arg("text"), Arg("strlist"), Arg("title"), Arg("primary_action"), Arg("secondary_action"), Arg("dont_ask_again_name") = static_cast<const QString &>(QString()), Arg("options") = static_cast<KMessageBox::Options>(KMessageBox::Options(KMessageBox::Notify | KMessageBox::Dangerous)));
    rb_mKMessageBox.define_module_function("warning_continue_cancel", &KMessageBox::warningContinueCancel, Arg("parent"), Arg("text"), Arg("title") = static_cast<const QString &>(QString()), Arg("button_continue") = static_cast<const KGuiItem &>(KStandardGuiItem::cont()), Arg("button_cancel") = static_cast<const KGuiItem &>(KStandardGuiItem::cancel()), Arg("dont_ask_again_name") = static_cast<const QString &>(QString()), Arg("options") = static_cast<KMessageBox::Options>(KMessageBox::Notify));
    rb_mKMessageBox.define_module_function("warning_continue_cancel_detailed", &KMessageBox::warningContinueCancelDetailed, Arg("parent"), Arg("text"), Arg("title") = static_cast<const QString &>(QString()), Arg("button_continue") = static_cast<const KGuiItem &>(KStandardGuiItem::cont()), Arg("button_cancel") = static_cast<const KGuiItem &>(KStandardGuiItem::cancel()), Arg("dont_ask_again_name") = static_cast<const QString &>(QString()), Arg("options") = static_cast<KMessageBox::Options>(KMessageBox::Notify), Arg("details") = static_cast<const QString &>(QString()));
    rb_mKMessageBox.define_module_function("warning_continue_cancel_list", &KMessageBox::warningContinueCancelList, Arg("parent"), Arg("text"), Arg("strlist"), Arg("title") = static_cast<const QString &>(QString()), Arg("button_continue") = static_cast<const KGuiItem &>(KStandardGuiItem::cont()), Arg("button_cancel") = static_cast<const KGuiItem &>(KStandardGuiItem::cancel()), Arg("dont_ask_again_name") = static_cast<const QString &>(QString()), Arg("options") = static_cast<KMessageBox::Options>(KMessageBox::Notify));
    rb_mKMessageBox.define_module_function("warning_two_actions_cancel", &KMessageBox::warningTwoActionsCancel, Arg("parent"), Arg("text"), Arg("title"), Arg("primary_action"), Arg("secondary_action"), Arg("cancel_action") = static_cast<const KGuiItem &>(KStandardGuiItem::cancel()), Arg("dont_ask_again_name") = static_cast<const QString &>(QString()), Arg("options") = static_cast<KMessageBox::Options>(KMessageBox::Options(KMessageBox::Notify | KMessageBox::Dangerous)));
    rb_mKMessageBox.define_module_function("warning_two_actions_cancel_list", &KMessageBox::warningTwoActionsCancelList, Arg("parent"), Arg("text"), Arg("strlist"), Arg("title"), Arg("primary_action"), Arg("secondary_action"), Arg("cancel_action") = static_cast<const KGuiItem &>(KStandardGuiItem::cancel()), Arg("dont_ask_again_name") = static_cast<const QString &>(QString()), Arg("options") = static_cast<KMessageBox::Options>(KMessageBox::Options(KMessageBox::Notify | KMessageBox::Dangerous)));
    rb_mKMessageBox.define_module_function<void (*)(QWidget *, const QString &, const QString &, KMessageBox::Options)>("error", &KMessageBox::error, Arg("parent"), Arg("text"), Arg("title") = static_cast<const QString &>(QString()), Arg("options") = static_cast<KMessageBox::Options>(KMessageBox::Notify));
    rb_mKMessageBox.define_module_function<void (*)(QWidget *, const QString &, const QString &, const KGuiItem &, KMessageBox::Options)>("error", &KMessageBox::error, Arg("parent"), Arg("text"), Arg("title"), Arg("button_ok"), Arg("options") = static_cast<KMessageBox::Options>(KMessageBox::Notify));
    rb_mKMessageBox.define_module_function("error_list", &KMessageBox::errorList, Arg("parent"), Arg("text"), Arg("strlist"), Arg("title") = static_cast<const QString &>(QString()), Arg("options") = static_cast<KMessageBox::Options>(KMessageBox::Notify));
    rb_mKMessageBox.define_module_function<void (*)(QWidget *, const QString &, const QString &, const QString &, KMessageBox::Options)>("detailed_error", &KMessageBox::detailedError, Arg("parent"), Arg("text"), Arg("details"), Arg("title") = static_cast<const QString &>(QString()), Arg("options") = static_cast<KMessageBox::Options>(KMessageBox::Notify));
    rb_mKMessageBox.define_module_function<void (*)(QWidget *, const QString &, const QString &, const QString &, const KGuiItem &, KMessageBox::Options)>("detailed_error", &KMessageBox::detailedError, Arg("parent"), Arg("text"), Arg("details"), Arg("title"), Arg("button_ok"), Arg("options") = static_cast<KMessageBox::Options>(KMessageBox::Notify));
    rb_mKMessageBox.define_module_function("information", &KMessageBox::information, Arg("parent"), Arg("text"), Arg("title") = static_cast<const QString &>(QString()), Arg("dont_show_again_name") = static_cast<const QString &>(QString()), Arg("options") = static_cast<KMessageBox::Options>(KMessageBox::Notify));
    rb_mKMessageBox.define_module_function("information_list", &KMessageBox::informationList, Arg("parent"), Arg("text"), Arg("strlist"), Arg("title") = static_cast<const QString &>(QString()), Arg("dont_show_again_name") = static_cast<const QString &>(QString()), Arg("options") = static_cast<KMessageBox::Options>(KMessageBox::Notify));
    rb_mKMessageBox.define_module_function("enable_all_messages", &KMessageBox::enableAllMessages);
    rb_mKMessageBox.define_module_function("enable_message", &KMessageBox::enableMessage, Arg("dont_show_again_name"));
    rb_mKMessageBox.define_module_function("message_box", &KMessageBox::messageBox, Arg("parent"), Arg("type"), Arg("text"), Arg("title"), Arg("primary_action"), Arg("secondary_action"), Arg("cancel_action") = static_cast<const KGuiItem &>(KStandardGuiItem::cancel()), Arg("dont_show_ask_again_name") = static_cast<const QString &>(QString()), Arg("options") = static_cast<KMessageBox::Options>(KMessageBox::Notify));
    rb_mKMessageBox.define_module_function("should_be_shown_two_actions", &KMessageBox::shouldBeShownTwoActions, Arg("dont_show_again_name"), Arg("result"));
    rb_mKMessageBox.define_module_function("should_be_shown_continue", &KMessageBox::shouldBeShownContinue, Arg("dont_show_again_name"));
    rb_mKMessageBox.define_module_function("save_dont_show_again_two_actions", &KMessageBox::saveDontShowAgainTwoActions, Arg("dont_show_again_name"), Arg("result"));
    rb_mKMessageBox.define_module_function("save_dont_show_again_continue", &KMessageBox::saveDontShowAgainContinue, Arg("dont_show_again_name"));
    rb_mKMessageBox.define_module_function("set_dont_show_again_config", &KMessageBox::setDontShowAgainConfig, Arg("cfg"));
    rb_mKMessageBox.define_module_function("set_dont_show_again_interface", &KMessageBox::setDontShowAgainInterface, Arg("dont_ask_again_interface"));
    rb_mKMessageBox.define_module_function("set_notify_interface", &KMessageBox::setNotifyInterface, Arg("notify_interface"));
    rb_mKMessageBox.define_module_function<QDialogButtonBox::StandardButton (*)(QDialog *, QDialogButtonBox *, QMessageBox::Icon, const QString &, const QStringList &, const QString &, bool *, KMessageBox::Options, const QString &)>("create_k_message_box", &KMessageBox::createKMessageBox, Arg("dialog"), Arg("buttons"), Arg("icon"), Arg("text"), Arg("strlist"), Arg("ask"), Arg("checkbox_return"), Arg("options"), Arg("details") = static_cast<const QString &>(QString()));
    rb_mKMessageBox.define_module_function<QDialogButtonBox::StandardButton (*)(QDialog *, QDialogButtonBox *, const QIcon &, const QString &, const QStringList &, const QString &, bool *, KMessageBox::Options, const QString &, QMessageBox::Icon)>("create_k_message_box", &KMessageBox::createKMessageBox, Arg("dialog"), Arg("buttons"), Arg("icon"), Arg("text"), Arg("strlist"), Arg("ask"), Arg("checkbox_return"), Arg("options"), Arg("details") = static_cast<const QString &>(QString()), Arg("notify_type") = static_cast<QMessageBox::Icon>(QMessageBox::Information));
    rb_mKMessageBox.define_module_function("question_two_actions_w_id", &KMessageBox::questionTwoActionsWId, Arg("parent_id"), Arg("text"), Arg("title"), Arg("primary_action"), Arg("secondary_action"), Arg("dont_ask_again_name") = static_cast<const QString &>(QString()), Arg("options") = static_cast<KMessageBox::Options>(KMessageBox::Notify));
    rb_mKMessageBox.define_module_function("question_two_actions_cancel_w_id", &KMessageBox::questionTwoActionsCancelWId, Arg("parent_id"), Arg("text"), Arg("title"), Arg("primary_action"), Arg("secondary_action"), Arg("cancel_action") = static_cast<const KGuiItem &>(KStandardGuiItem::cancel()), Arg("dont_ask_again_name") = static_cast<const QString &>(QString()), Arg("options") = static_cast<KMessageBox::Options>(KMessageBox::Notify));
    rb_mKMessageBox.define_module_function("question_two_actions_list_w_id", &KMessageBox::questionTwoActionsListWId, Arg("parent_id"), Arg("text"), Arg("strlist"), Arg("title"), Arg("primary_action"), Arg("secondary_action"), Arg("dont_ask_again_name") = static_cast<const QString &>(QString()), Arg("options") = static_cast<KMessageBox::Options>(KMessageBox::Notify));
    rb_mKMessageBox.define_module_function("warning_two_actions_w_id", &KMessageBox::warningTwoActionsWId, Arg("parent_id"), Arg("text"), Arg("title"), Arg("primary_action"), Arg("secondary_action"), Arg("dont_ask_again_name") = static_cast<const QString &>(QString()), Arg("options") = static_cast<KMessageBox::Options>(KMessageBox::Options(KMessageBox::Notify | KMessageBox::Dangerous)));
    rb_mKMessageBox.define_module_function("warning_two_actions_list_w_id", &KMessageBox::warningTwoActionsListWId, Arg("parent_id"), Arg("text"), Arg("strlist"), Arg("title"), Arg("primary_action"), Arg("secondary_action"), Arg("dont_ask_again_name") = static_cast<const QString &>(QString()), Arg("options") = static_cast<KMessageBox::Options>(KMessageBox::Options(KMessageBox::Notify | KMessageBox::Dangerous)));
    rb_mKMessageBox.define_module_function("warning_continue_cancel_w_id", &KMessageBox::warningContinueCancelWId, Arg("parent_id"), Arg("text"), Arg("title") = static_cast<const QString &>(QString()), Arg("button_continue") = static_cast<const KGuiItem &>(KStandardGuiItem::cont()), Arg("button_cancel") = static_cast<const KGuiItem &>(KStandardGuiItem::cancel()), Arg("dont_ask_again_name") = static_cast<const QString &>(QString()), Arg("options") = static_cast<KMessageBox::Options>(KMessageBox::Notify));
    rb_mKMessageBox.define_module_function("warning_continue_cancel_list_w_id", &KMessageBox::warningContinueCancelListWId, Arg("parent_id"), Arg("text"), Arg("strlist"), Arg("title") = static_cast<const QString &>(QString()), Arg("button_continue") = static_cast<const KGuiItem &>(KStandardGuiItem::cont()), Arg("button_cancel") = static_cast<const KGuiItem &>(KStandardGuiItem::cancel()), Arg("dont_ask_again_name") = static_cast<const QString &>(QString()), Arg("options") = static_cast<KMessageBox::Options>(KMessageBox::Notify));
    rb_mKMessageBox.define_module_function("warning_two_actions_cancel_w_id", &KMessageBox::warningTwoActionsCancelWId, Arg("parent_id"), Arg("text"), Arg("title"), Arg("primary_action"), Arg("secondary_action"), Arg("cancel_action") = static_cast<const KGuiItem &>(KStandardGuiItem::cancel()), Arg("dont_ask_again_name") = static_cast<const QString &>(QString()), Arg("options") = static_cast<KMessageBox::Options>(KMessageBox::Options(KMessageBox::Notify | KMessageBox::Dangerous)));
    rb_mKMessageBox.define_module_function("warning_two_actions_cancel_list_w_id", &KMessageBox::warningTwoActionsCancelListWId, Arg("parent_id"), Arg("text"), Arg("strlist"), Arg("title"), Arg("primary_action"), Arg("secondary_action"), Arg("cancel_action") = static_cast<const KGuiItem &>(KStandardGuiItem::cancel()), Arg("dont_ask_again_name") = static_cast<const QString &>(QString()), Arg("options") = static_cast<KMessageBox::Options>(KMessageBox::Options(KMessageBox::Notify | KMessageBox::Dangerous)));
    rb_mKMessageBox.define_module_function("error_w_id", &KMessageBox::errorWId, Arg("parent_id"), Arg("text"), Arg("title") = static_cast<const QString &>(QString()), Arg("options") = static_cast<KMessageBox::Options>(KMessageBox::Notify));
    rb_mKMessageBox.define_module_function("error_list_w_id", &KMessageBox::errorListWId, Arg("parent_id"), Arg("text"), Arg("strlist"), Arg("title") = static_cast<const QString &>(QString()), Arg("options") = static_cast<KMessageBox::Options>(KMessageBox::Notify));
    rb_mKMessageBox.define_module_function<void (*)(WId, const QString &, const QString &, const QString &, KMessageBox::Options)>("detailed_error_w_id", &KMessageBox::detailedErrorWId, Arg("parent_id"), Arg("text"), Arg("details"), Arg("title") = static_cast<const QString &>(QString()), Arg("options") = static_cast<KMessageBox::Options>(KMessageBox::Notify));
    rb_mKMessageBox.define_module_function<void (*)(WId, const QString &, const QString &, const QString &, const KGuiItem &, KMessageBox::Options)>("detailed_error_w_id", &KMessageBox::detailedErrorWId, Arg("parent_id"), Arg("text"), Arg("details"), Arg("title"), Arg("button_ok"), Arg("options") = static_cast<KMessageBox::Options>(KMessageBox::Notify));
    rb_mKMessageBox.define_module_function("information_w_id", &KMessageBox::informationWId, Arg("parent_id"), Arg("text"), Arg("title") = static_cast<const QString &>(QString()), Arg("dont_show_again_name") = static_cast<const QString &>(QString()), Arg("options") = static_cast<KMessageBox::Options>(KMessageBox::Notify));
    rb_mKMessageBox.define_module_function("information_list_w_id", &KMessageBox::informationListWId, Arg("parent_id"), Arg("text"), Arg("strlist"), Arg("title") = static_cast<const QString &>(QString()), Arg("dont_show_again_name") = static_cast<const QString &>(QString()), Arg("options") = static_cast<KMessageBox::Options>(KMessageBox::Notify));
    rb_mKMessageBox.define_module_function("message_box_w_id", &KMessageBox::messageBoxWId, Arg("parent_id"), Arg("type"), Arg("text"), Arg("title"), Arg("primary_action"), Arg("secondary_action"), Arg("cancel_action") = static_cast<const KGuiItem &>(KStandardGuiItem::cancel()), Arg("dont_show_ask_again_name") = static_cast<const QString &>(QString()), Arg("options") = static_cast<KMessageBox::Options>(KMessageBox::Notify));
}
