# frozen_string_literal: true

source "https://rubygems.org"

# Specify your gem's dependencies in rspec.gemspec
gemspec

# rake
gem "irb"
gem "rake", "~> 13.0"
gem "rake-compiler"

# lint
gem "rubocop"
gem "standard"

# test
gem "rspec"

# doc
gem "yard"
gem "redcarpet"

# lsp
gem "solargraph"
