# frozen_string_literal: true

source "https://rubygems.org"

# Specify your gem's dependencies in qt.gemspec
gemspec

# ruby-qt6
%w[
  rice
  qtcore qtgui qtwidgets qtnetwork qtprintsupport
  qtqml qtquick qtquickcontrols2 qtquickwidgets
  qtmultimedia qtmultimediawidgets
  qtwebenginecore qtwebenginewidgets qtwebview
  qtuitools
].each do |lib|
  gem "ruby-qt6-#{lib}", path: "../#{lib}"
end

# ruby-qt6 - linux
%w[
  qtdbus
].each do |lib|
  next unless RUBY_PLATFORM.downcase.include?("linux")
  gem "ruby-qt6-#{lib}", path: "../#{lib}"
end

# rake
gem "irb"
gem "rake", "~> 13.0"

# lint
gem "rubocop"
gem "standard"

# test
gem "rspec"

# doc
gem "yard"
gem "redcarpet"

# lsp
gem "solargraph"
