# frozen_string_literal: true

source "https://rubygems.org"

# Specify your gem's dependencies in kdeframeworks.gemspec
gemspec

# ruby-qt6
%w[
  rice
  qtcore qtgui qtwidgets
  kcoreaddons kguiaddons kwidgetsaddons
].each do |lib|
  gem "ruby-qt6-#{lib}", path: "../#{lib}"
end

# rake
gem "irb"
gem "rake", "~> 13.0"

# lint
gem "rubocop"
gem "standard"

# test
gem "rspec"

# doc
gem "yard"
gem "redcarpet"

# lsp
gem "solargraph"
