#include "qchar-rb.hpp"
#include <qchar.h>

#include <QString>

using namespace Rice;

Rice::Class rb_cQChar;

void Init_qchar(Rice::Module rb_mQt6QtCore)
{
    rb_cQChar =
        // RubyQt6::QtCore::QChar
        define_class_under<QChar>(rb_mQt6QtCore, "QChar")
            // RubyQt6-Defined Functions
            .define_method("to_std_string", [](QChar *self) -> std::string { return QString(*self).toStdString(); })
            // Constructor
            .define_constructor(Constructor<QChar, int>(), Arg("code"))
            // Public Functions
            .define_method<QChar::Category (QChar::*)() const noexcept>("category", &QChar::category)
            .define_method("cell", &QChar::cell)
            .define_method<unsigned char (QChar::*)() const noexcept>("combining_class", &QChar::combiningClass)
            .define_method<QString (QChar::*)() const>("decomposition", &QChar::decomposition)
            .define_method<QChar::Decomposition (QChar::*)() const noexcept>("decomposition_tag", &QChar::decompositionTag)
            .define_method<int (QChar::*)() const noexcept>("digit_value", &QChar::digitValue)
            .define_method<QChar::Direction (QChar::*)() const noexcept>("direction", &QChar::direction)
            .define_method<bool (QChar::*)() const noexcept>("has_mirrored", &QChar::hasMirrored)
            .define_method<bool (QChar::*)() const noexcept>("digit?", &QChar::isDigit)
            .define_method<bool (QChar::*)() const noexcept>("high_surrogate?", &QChar::isHighSurrogate)
            .define_method<bool (QChar::*)() const noexcept>("letter?", &QChar::isLetter)
            .define_method<bool (QChar::*)() const noexcept>("letter_or_number?", &QChar::isLetterOrNumber)
            .define_method<bool (QChar::*)() const noexcept>("low_surrogate?", &QChar::isLowSurrogate)
            .define_method<bool (QChar::*)() const noexcept>("lower?", &QChar::isLower)
            .define_method<bool (QChar::*)() const noexcept>("mark?", &QChar::isMark)
            .define_method<bool (QChar::*)() const noexcept>("non_character?", &QChar::isNonCharacter)
            .define_method("null?", &QChar::isNull)
            .define_method<bool (QChar::*)() const noexcept>("number?", &QChar::isNumber)
            .define_method<bool (QChar::*)() const noexcept>("print?", &QChar::isPrint)
            .define_method<bool (QChar::*)() const noexcept>("punct?", &QChar::isPunct)
            .define_method<bool (QChar::*)() const noexcept>("space?", &QChar::isSpace)
            .define_method<bool (QChar::*)() const noexcept>("surrogate?", &QChar::isSurrogate)
            .define_method<bool (QChar::*)() const noexcept>("symbol?", &QChar::isSymbol)
            .define_method<bool (QChar::*)() const noexcept>("title_case?", &QChar::isTitleCase)
            .define_method<bool (QChar::*)() const noexcept>("upper?", &QChar::isUpper)
            .define_method<QChar::JoiningType (QChar::*)() const noexcept>("joining_type", &QChar::joiningType)
            .define_method<QChar (QChar::*)() const noexcept>("mirrored_char", &QChar::mirroredChar)
            .define_method("row", &QChar::row)
            .define_method<QChar::Script (QChar::*)() const noexcept>("script", &QChar::script)
            .define_method("set_cell", &QChar::setCell, Arg("acell"))
            .define_method("set_row", &QChar::setRow, Arg("arow"))
            .define_method<QChar (QChar::*)() const noexcept>("to_case_folded", &QChar::toCaseFolded)
            .define_method("to_latin1", &QChar::toLatin1)
            .define_method<QChar (QChar::*)() const noexcept>("to_lower", &QChar::toLower)
            .define_method<QChar (QChar::*)() const noexcept>("to_title_case", &QChar::toTitleCase)
            .define_method<QChar (QChar::*)() const noexcept>("to_upper", &QChar::toUpper)
            // .define_method<char16_t (QChar::*)() const noexcept>("unicode", &QChar::unicode)
            .define_method<QChar::UnicodeVersion (QChar::*)() const noexcept>("unicode_version", &QChar::unicodeVersion);

    Enum<QChar::Category> rb_cQCharCategory =
        // RubyQt6::QtCore::QChar::Category
        define_enum_under<QChar::Category>("Category", rb_cQChar)
            .define_value("Mark_NonSpacing", QChar::Category::Mark_NonSpacing)
            .define_value("Mark_SpacingCombining", QChar::Category::Mark_SpacingCombining)
            .define_value("Mark_Enclosing", QChar::Category::Mark_Enclosing)
            .define_value("Number_DecimalDigit", QChar::Category::Number_DecimalDigit)
            .define_value("Number_Letter", QChar::Category::Number_Letter)
            .define_value("Number_Other", QChar::Category::Number_Other)
            .define_value("Separator_Space", QChar::Category::Separator_Space)
            .define_value("Separator_Line", QChar::Category::Separator_Line)
            .define_value("Separator_Paragraph", QChar::Category::Separator_Paragraph)
            .define_value("Other_Control", QChar::Category::Other_Control)
            .define_value("Other_Format", QChar::Category::Other_Format)
            .define_value("Other_Surrogate", QChar::Category::Other_Surrogate)
            .define_value("Other_PrivateUse", QChar::Category::Other_PrivateUse)
            .define_value("Other_NotAssigned", QChar::Category::Other_NotAssigned)
            .define_value("Letter_Uppercase", QChar::Category::Letter_Uppercase)
            .define_value("Letter_Lowercase", QChar::Category::Letter_Lowercase)
            .define_value("Letter_Titlecase", QChar::Category::Letter_Titlecase)
            .define_value("Letter_Modifier", QChar::Category::Letter_Modifier)
            .define_value("Letter_Other", QChar::Category::Letter_Other)
            .define_value("Punctuation_Connector", QChar::Category::Punctuation_Connector)
            .define_value("Punctuation_Dash", QChar::Category::Punctuation_Dash)
            .define_value("Punctuation_Open", QChar::Category::Punctuation_Open)
            .define_value("Punctuation_Close", QChar::Category::Punctuation_Close)
            .define_value("Punctuation_InitialQuote", QChar::Category::Punctuation_InitialQuote)
            .define_value("Punctuation_FinalQuote", QChar::Category::Punctuation_FinalQuote)
            .define_value("Punctuation_Other", QChar::Category::Punctuation_Other)
            .define_value("Symbol_Math", QChar::Category::Symbol_Math)
            .define_value("Symbol_Currency", QChar::Category::Symbol_Currency)
            .define_value("Symbol_Modifier", QChar::Category::Symbol_Modifier)
            .define_value("Symbol_Other", QChar::Category::Symbol_Other);

    Enum<QChar::CombiningClass> rb_cQCharCombiningClass =
        // RubyQt6::QtCore::QChar::CombiningClass
        define_enum_under<QChar::CombiningClass>("CombiningClass", rb_cQChar)
            .define_value("Combining_BelowLeftAttached", QChar::CombiningClass::Combining_BelowLeftAttached)
            .define_value("Combining_BelowAttached", QChar::CombiningClass::Combining_BelowAttached)
            .define_value("Combining_BelowRightAttached", QChar::CombiningClass::Combining_BelowRightAttached)
            .define_value("Combining_LeftAttached", QChar::CombiningClass::Combining_LeftAttached)
            .define_value("Combining_RightAttached", QChar::CombiningClass::Combining_RightAttached)
            .define_value("Combining_AboveLeftAttached", QChar::CombiningClass::Combining_AboveLeftAttached)
            .define_value("Combining_AboveAttached", QChar::CombiningClass::Combining_AboveAttached)
            .define_value("Combining_AboveRightAttached", QChar::CombiningClass::Combining_AboveRightAttached)
            .define_value("Combining_BelowLeft", QChar::CombiningClass::Combining_BelowLeft)
            .define_value("Combining_Below", QChar::CombiningClass::Combining_Below)
            .define_value("Combining_BelowRight", QChar::CombiningClass::Combining_BelowRight)
            .define_value("Combining_Left", QChar::CombiningClass::Combining_Left)
            .define_value("Combining_Right", QChar::CombiningClass::Combining_Right)
            .define_value("Combining_AboveLeft", QChar::CombiningClass::Combining_AboveLeft)
            .define_value("Combining_Above", QChar::CombiningClass::Combining_Above)
            .define_value("Combining_AboveRight", QChar::CombiningClass::Combining_AboveRight)
            .define_value("Combining_DoubleBelow", QChar::CombiningClass::Combining_DoubleBelow)
            .define_value("Combining_DoubleAbove", QChar::CombiningClass::Combining_DoubleAbove)
            .define_value("Combining_IotaSubscript", QChar::CombiningClass::Combining_IotaSubscript);

    Enum<QChar::Decomposition> rb_cQCharDecomposition =
        // RubyQt6::QtCore::QChar::Decomposition
        define_enum_under<QChar::Decomposition>("Decomposition", rb_cQChar)
            .define_value("NoDecomposition", QChar::Decomposition::NoDecomposition)
            .define_value("Canonical", QChar::Decomposition::Canonical)
            .define_value("Font", QChar::Decomposition::Font)
            .define_value("NoBreak", QChar::Decomposition::NoBreak)
            .define_value("Initial", QChar::Decomposition::Initial)
            .define_value("Medial", QChar::Decomposition::Medial)
            .define_value("Final", QChar::Decomposition::Final)
            .define_value("Isolated", QChar::Decomposition::Isolated)
            .define_value("Circle", QChar::Decomposition::Circle)
            .define_value("Super", QChar::Decomposition::Super)
            .define_value("Sub", QChar::Decomposition::Sub)
            .define_value("Vertical", QChar::Decomposition::Vertical)
            .define_value("Wide", QChar::Decomposition::Wide)
            .define_value("Narrow", QChar::Decomposition::Narrow)
            .define_value("Small", QChar::Decomposition::Small)
            .define_value("Square", QChar::Decomposition::Square)
            .define_value("Compat", QChar::Decomposition::Compat)
            .define_value("Fraction", QChar::Decomposition::Fraction);

    Enum<QChar::Direction> rb_cQCharDirection =
        // RubyQt6::QtCore::QChar::Direction
        define_enum_under<QChar::Direction>("Direction", rb_cQChar)
            .define_value("DirL", QChar::Direction::DirL)
            .define_value("DirR", QChar::Direction::DirR)
            .define_value("DirEN", QChar::Direction::DirEN)
            .define_value("DirES", QChar::Direction::DirES)
            .define_value("DirET", QChar::Direction::DirET)
            .define_value("DirAN", QChar::Direction::DirAN)
            .define_value("DirCS", QChar::Direction::DirCS)
            .define_value("DirB", QChar::Direction::DirB)
            .define_value("DirS", QChar::Direction::DirS)
            .define_value("DirWS", QChar::Direction::DirWS)
            .define_value("DirON", QChar::Direction::DirON)
            .define_value("DirLRE", QChar::Direction::DirLRE)
            .define_value("DirLRO", QChar::Direction::DirLRO)
            .define_value("DirAL", QChar::Direction::DirAL)
            .define_value("DirRLE", QChar::Direction::DirRLE)
            .define_value("DirRLO", QChar::Direction::DirRLO)
            .define_value("DirPDF", QChar::Direction::DirPDF)
            .define_value("DirNSM", QChar::Direction::DirNSM)
            .define_value("DirBN", QChar::Direction::DirBN)
            .define_value("DirLRI", QChar::Direction::DirLRI)
            .define_value("DirRLI", QChar::Direction::DirRLI)
            .define_value("DirFSI", QChar::Direction::DirFSI)
            .define_value("DirPDI", QChar::Direction::DirPDI);


    Enum<QChar::JoiningType> rb_cQCharJoiningType =
        // RubyQt6::QtCore::QChar::JoiningType
        define_enum_under<QChar::JoiningType>("JoiningType", rb_cQChar)
            .define_value("Joining_None", QChar::JoiningType::Joining_None)
            .define_value("Joining_Causing", QChar::JoiningType::Joining_Causing)
            .define_value("Joining_Dual", QChar::JoiningType::Joining_Dual)
            .define_value("Joining_Right", QChar::JoiningType::Joining_Right)
            .define_value("Joining_Left", QChar::JoiningType::Joining_Left)
            .define_value("Joining_Transparent", QChar::JoiningType::Joining_Transparent);

    Enum<QChar::Script> rb_cQCharScript =
        // RubyQt6::QtCore::QChar::Script
        define_enum_under<QChar::Script>("Script", rb_cQChar)
            .define_value("Script_Unknown", QChar::Script::Script_Unknown)
            .define_value("Script_Inherited", QChar::Script::Script_Inherited)
            .define_value("Script_Common", QChar::Script::Script_Common)
            .define_value("Script_Latin", QChar::Script::Script_Latin)
            .define_value("Script_Greek", QChar::Script::Script_Greek)
            .define_value("Script_Cyrillic", QChar::Script::Script_Cyrillic)
            .define_value("Script_Armenian", QChar::Script::Script_Armenian)
            .define_value("Script_Hebrew", QChar::Script::Script_Hebrew)
            .define_value("Script_Arabic", QChar::Script::Script_Arabic)
            .define_value("Script_Syriac", QChar::Script::Script_Syriac)
            .define_value("Script_Thaana", QChar::Script::Script_Thaana)
            .define_value("Script_Devanagari", QChar::Script::Script_Devanagari)
            .define_value("Script_Bengali", QChar::Script::Script_Bengali)
            .define_value("Script_Gurmukhi", QChar::Script::Script_Gurmukhi)
            .define_value("Script_Gujarati", QChar::Script::Script_Gujarati)
            .define_value("Script_Oriya", QChar::Script::Script_Oriya)
            .define_value("Script_Tamil", QChar::Script::Script_Tamil)
            .define_value("Script_Telugu", QChar::Script::Script_Telugu)
            .define_value("Script_Kannada", QChar::Script::Script_Kannada)
            .define_value("Script_Malayalam", QChar::Script::Script_Malayalam)
            .define_value("Script_Sinhala", QChar::Script::Script_Sinhala)
            .define_value("Script_Thai", QChar::Script::Script_Thai)
            .define_value("Script_Lao", QChar::Script::Script_Lao)
            .define_value("Script_Tibetan", QChar::Script::Script_Tibetan)
            .define_value("Script_Myanmar", QChar::Script::Script_Myanmar)
            .define_value("Script_Georgian", QChar::Script::Script_Georgian)
            .define_value("Script_Hangul", QChar::Script::Script_Hangul)
            .define_value("Script_Ethiopic", QChar::Script::Script_Ethiopic)
            .define_value("Script_Cherokee", QChar::Script::Script_Cherokee)
            .define_value("Script_CanadianAboriginal", QChar::Script::Script_CanadianAboriginal)
            .define_value("Script_Ogham", QChar::Script::Script_Ogham)
            .define_value("Script_Runic", QChar::Script::Script_Runic)
            .define_value("Script_Khmer", QChar::Script::Script_Khmer)
            .define_value("Script_Mongolian", QChar::Script::Script_Mongolian)
            .define_value("Script_Hiragana", QChar::Script::Script_Hiragana)
            .define_value("Script_Katakana", QChar::Script::Script_Katakana)
            .define_value("Script_Bopomofo", QChar::Script::Script_Bopomofo)
            .define_value("Script_Han", QChar::Script::Script_Han)
            .define_value("Script_Yi", QChar::Script::Script_Yi)
            .define_value("Script_OldItalic", QChar::Script::Script_OldItalic)
            .define_value("Script_Gothic", QChar::Script::Script_Gothic)
            .define_value("Script_Deseret", QChar::Script::Script_Deseret)
            .define_value("Script_Tagalog", QChar::Script::Script_Tagalog)
            .define_value("Script_Hanunoo", QChar::Script::Script_Hanunoo)
            .define_value("Script_Buhid", QChar::Script::Script_Buhid)
            .define_value("Script_Tagbanwa", QChar::Script::Script_Tagbanwa)
            .define_value("Script_Coptic", QChar::Script::Script_Coptic)
            .define_value("Script_Limbu", QChar::Script::Script_Limbu)
            .define_value("Script_TaiLe", QChar::Script::Script_TaiLe)
            .define_value("Script_LinearB", QChar::Script::Script_LinearB)
            .define_value("Script_Ugaritic", QChar::Script::Script_Ugaritic)
            .define_value("Script_Shavian", QChar::Script::Script_Shavian)
            .define_value("Script_Osmanya", QChar::Script::Script_Osmanya)
            .define_value("Script_Cypriot", QChar::Script::Script_Cypriot)
            .define_value("Script_Braille", QChar::Script::Script_Braille)
            .define_value("Script_Buginese", QChar::Script::Script_Buginese)
            .define_value("Script_NewTaiLue", QChar::Script::Script_NewTaiLue)
            .define_value("Script_Glagolitic", QChar::Script::Script_Glagolitic)
            .define_value("Script_Tifinagh", QChar::Script::Script_Tifinagh)
            .define_value("Script_SylotiNagri", QChar::Script::Script_SylotiNagri)
            .define_value("Script_OldPersian", QChar::Script::Script_OldPersian)
            .define_value("Script_Kharoshthi", QChar::Script::Script_Kharoshthi)
            .define_value("Script_Balinese", QChar::Script::Script_Balinese)
            .define_value("Script_Cuneiform", QChar::Script::Script_Cuneiform)
            .define_value("Script_Phoenician", QChar::Script::Script_Phoenician)
            .define_value("Script_PhagsPa", QChar::Script::Script_PhagsPa)
            .define_value("Script_Nko", QChar::Script::Script_Nko)
            .define_value("Script_Sundanese", QChar::Script::Script_Sundanese)
            .define_value("Script_Lepcha", QChar::Script::Script_Lepcha)
            .define_value("Script_OlChiki", QChar::Script::Script_OlChiki)
            .define_value("Script_Vai", QChar::Script::Script_Vai)
            .define_value("Script_Saurashtra", QChar::Script::Script_Saurashtra)
            .define_value("Script_KayahLi", QChar::Script::Script_KayahLi)
            .define_value("Script_Rejang", QChar::Script::Script_Rejang)
            .define_value("Script_Lycian", QChar::Script::Script_Lycian)
            .define_value("Script_Carian", QChar::Script::Script_Carian)
            .define_value("Script_Lydian", QChar::Script::Script_Lydian)
            .define_value("Script_Cham", QChar::Script::Script_Cham)
            .define_value("Script_TaiTham", QChar::Script::Script_TaiTham)
            .define_value("Script_TaiViet", QChar::Script::Script_TaiViet)
            .define_value("Script_Avestan", QChar::Script::Script_Avestan)
            .define_value("Script_EgyptianHieroglyphs", QChar::Script::Script_EgyptianHieroglyphs)
            .define_value("Script_Samaritan", QChar::Script::Script_Samaritan)
            .define_value("Script_Lisu", QChar::Script::Script_Lisu)
            .define_value("Script_Bamum", QChar::Script::Script_Bamum)
            .define_value("Script_Javanese", QChar::Script::Script_Javanese)
            .define_value("Script_MeeteiMayek", QChar::Script::Script_MeeteiMayek)
            .define_value("Script_ImperialAramaic", QChar::Script::Script_ImperialAramaic)
            .define_value("Script_OldSouthArabian", QChar::Script::Script_OldSouthArabian)
            .define_value("Script_InscriptionalParthian", QChar::Script::Script_InscriptionalParthian)
            .define_value("Script_InscriptionalPahlavi", QChar::Script::Script_InscriptionalPahlavi)
            .define_value("Script_OldTurkic", QChar::Script::Script_OldTurkic)
            .define_value("Script_Kaithi", QChar::Script::Script_Kaithi)
            .define_value("Script_Batak", QChar::Script::Script_Batak)
            .define_value("Script_Brahmi", QChar::Script::Script_Brahmi)
            .define_value("Script_Mandaic", QChar::Script::Script_Mandaic)
            .define_value("Script_Chakma", QChar::Script::Script_Chakma)
            .define_value("Script_MeroiticCursive", QChar::Script::Script_MeroiticCursive)
            .define_value("Script_MeroiticHieroglyphs", QChar::Script::Script_MeroiticHieroglyphs)
            .define_value("Script_Miao", QChar::Script::Script_Miao)
            .define_value("Script_Sharada", QChar::Script::Script_Sharada)
            .define_value("Script_SoraSompeng", QChar::Script::Script_SoraSompeng)
            .define_value("Script_Takri", QChar::Script::Script_Takri)
            .define_value("Script_CaucasianAlbanian", QChar::Script::Script_CaucasianAlbanian)
            .define_value("Script_BassaVah", QChar::Script::Script_BassaVah)
            .define_value("Script_Duployan", QChar::Script::Script_Duployan)
            .define_value("Script_Elbasan", QChar::Script::Script_Elbasan)
            .define_value("Script_Grantha", QChar::Script::Script_Grantha)
            .define_value("Script_PahawhHmong", QChar::Script::Script_PahawhHmong)
            .define_value("Script_Khojki", QChar::Script::Script_Khojki)
            .define_value("Script_LinearA", QChar::Script::Script_LinearA)
            .define_value("Script_Mahajani", QChar::Script::Script_Mahajani)
            .define_value("Script_Manichaean", QChar::Script::Script_Manichaean)
            .define_value("Script_MendeKikakui", QChar::Script::Script_MendeKikakui)
            .define_value("Script_Modi", QChar::Script::Script_Modi)
            .define_value("Script_Mro", QChar::Script::Script_Mro)
            .define_value("Script_OldNorthArabian", QChar::Script::Script_OldNorthArabian)
            .define_value("Script_Nabataean", QChar::Script::Script_Nabataean)
            .define_value("Script_Palmyrene", QChar::Script::Script_Palmyrene)
            .define_value("Script_PauCinHau", QChar::Script::Script_PauCinHau)
            .define_value("Script_OldPermic", QChar::Script::Script_OldPermic)
            .define_value("Script_PsalterPahlavi", QChar::Script::Script_PsalterPahlavi)
            .define_value("Script_Siddham", QChar::Script::Script_Siddham)
            .define_value("Script_Khudawadi", QChar::Script::Script_Khudawadi)
            .define_value("Script_Tirhuta", QChar::Script::Script_Tirhuta)
            .define_value("Script_WarangCiti", QChar::Script::Script_WarangCiti)
            .define_value("Script_Ahom", QChar::Script::Script_Ahom)
            .define_value("Script_AnatolianHieroglyphs", QChar::Script::Script_AnatolianHieroglyphs)
            .define_value("Script_Hatran", QChar::Script::Script_Hatran)
            .define_value("Script_Multani", QChar::Script::Script_Multani)
            .define_value("Script_OldHungarian", QChar::Script::Script_OldHungarian)
            .define_value("Script_SignWriting", QChar::Script::Script_SignWriting)
            .define_value("Script_Adlam", QChar::Script::Script_Adlam)
            .define_value("Script_Bhaiksuki", QChar::Script::Script_Bhaiksuki)
            .define_value("Script_Marchen", QChar::Script::Script_Marchen)
            .define_value("Script_Newa", QChar::Script::Script_Newa)
            .define_value("Script_Osage", QChar::Script::Script_Osage)
            .define_value("Script_Tangut", QChar::Script::Script_Tangut)
            .define_value("Script_MasaramGondi", QChar::Script::Script_MasaramGondi)
            .define_value("Script_Nushu", QChar::Script::Script_Nushu)
            .define_value("Script_Soyombo", QChar::Script::Script_Soyombo)
            .define_value("Script_ZanabazarSquare", QChar::Script::Script_ZanabazarSquare)
            .define_value("Script_Dogra", QChar::Script::Script_Dogra)
            .define_value("Script_GunjalaGondi", QChar::Script::Script_GunjalaGondi)
            .define_value("Script_HanifiRohingya", QChar::Script::Script_HanifiRohingya)
            .define_value("Script_Makasar", QChar::Script::Script_Makasar)
            .define_value("Script_Medefaidrin", QChar::Script::Script_Medefaidrin)
            .define_value("Script_OldSogdian", QChar::Script::Script_OldSogdian)
            .define_value("Script_Sogdian", QChar::Script::Script_Sogdian)
            .define_value("Script_Elymaic", QChar::Script::Script_Elymaic)
            .define_value("Script_Nandinagari", QChar::Script::Script_Nandinagari)
            .define_value("Script_NyiakengPuachueHmong", QChar::Script::Script_NyiakengPuachueHmong)
            .define_value("Script_Wancho", QChar::Script::Script_Wancho)
            .define_value("Script_Chorasmian", QChar::Script::Script_Chorasmian)
            .define_value("Script_DivesAkuru", QChar::Script::Script_DivesAkuru)
            .define_value("Script_KhitanSmallScript", QChar::Script::Script_KhitanSmallScript)
            .define_value("Script_Yezidi", QChar::Script::Script_Yezidi)
            .define_value("Script_CyproMinoan", QChar::Script::Script_CyproMinoan)
            .define_value("Script_OldUyghur", QChar::Script::Script_OldUyghur)
            .define_value("Script_Tangsa", QChar::Script::Script_Tangsa)
            .define_value("Script_Toto", QChar::Script::Script_Toto)
            .define_value("Script_Vithkuqi", QChar::Script::Script_Vithkuqi)
            .define_value("Script_Kawi", QChar::Script::Script_Kawi)
            .define_value("Script_NagMundari", QChar::Script::Script_NagMundari)
            .define_value("Script_Garay", QChar::Script::Script_Garay)
            .define_value("Script_GurungKhema", QChar::Script::Script_GurungKhema)
            .define_value("Script_KiratRai", QChar::Script::Script_KiratRai)
            .define_value("Script_OlOnal", QChar::Script::Script_OlOnal)
            .define_value("Script_Sunuwar", QChar::Script::Script_Sunuwar)
            .define_value("Script_Todhri", QChar::Script::Script_Todhri)
            .define_value("Script_TuluTigalari", QChar::Script::Script_TuluTigalari)
            .define_value("ScriptCount", QChar::Script::ScriptCount);

    Enum<QChar::SpecialCharacter> rb_cQCharSpecialCharacter =
        // RubyQt6::QtCore::QChar::SpecialCharacter
        define_enum_under<QChar::SpecialCharacter>("SpecialCharacter", rb_cQChar)
            .define_value("Null", QChar::SpecialCharacter::Null)
            .define_value("Tabulation", QChar::SpecialCharacter::Tabulation)
            .define_value("LineFeed", QChar::SpecialCharacter::LineFeed)
            .define_value("FormFeed", QChar::SpecialCharacter::FormFeed)
            .define_value("CarriageReturn", QChar::SpecialCharacter::CarriageReturn)
            .define_value("Space", QChar::SpecialCharacter::Space)
            .define_value("Nbsp", QChar::SpecialCharacter::Nbsp)
            .define_value("SoftHyphen", QChar::SpecialCharacter::SoftHyphen)
            .define_value("ReplacementCharacter", QChar::SpecialCharacter::ReplacementCharacter)
            .define_value("ObjectReplacementCharacter", QChar::SpecialCharacter::ObjectReplacementCharacter)
            .define_value("ByteOrderMark", QChar::SpecialCharacter::ByteOrderMark)
            .define_value("ByteOrderSwapped", QChar::SpecialCharacter::ByteOrderSwapped)
            .define_value("ParagraphSeparator", QChar::SpecialCharacter::ParagraphSeparator)
            .define_value("LineSeparator", QChar::SpecialCharacter::LineSeparator)
            .define_value("VisualTabCharacter", QChar::SpecialCharacter::VisualTabCharacter)
            .define_value("LastValidCodePoint", QChar::SpecialCharacter::LastValidCodePoint);

    Enum<QChar::UnicodeVersion> rb_cQCharUnicodeVersion =
        // RubyQt6::QtCore::QChar::UnicodeVersion
        define_enum_under<QChar::UnicodeVersion>("UnicodeVersion", rb_cQChar)
            .define_value("Unicode_Unassigned", QChar::UnicodeVersion::Unicode_Unassigned)
            .define_value("Unicode_1_1", QChar::UnicodeVersion::Unicode_1_1)
            .define_value("Unicode_2_0", QChar::UnicodeVersion::Unicode_2_0)
            .define_value("Unicode_2_1_2", QChar::UnicodeVersion::Unicode_2_1_2)
            .define_value("Unicode_3_0", QChar::UnicodeVersion::Unicode_3_0)
            .define_value("Unicode_3_1", QChar::UnicodeVersion::Unicode_3_1)
            .define_value("Unicode_3_2", QChar::UnicodeVersion::Unicode_3_2)
            .define_value("Unicode_4_0", QChar::UnicodeVersion::Unicode_4_0)
            .define_value("Unicode_4_1", QChar::UnicodeVersion::Unicode_4_1)
            .define_value("Unicode_5_0", QChar::UnicodeVersion::Unicode_5_0)
            .define_value("Unicode_5_1", QChar::UnicodeVersion::Unicode_5_1)
            .define_value("Unicode_5_2", QChar::UnicodeVersion::Unicode_5_2)
            .define_value("Unicode_6_0", QChar::UnicodeVersion::Unicode_6_0)
            .define_value("Unicode_6_1", QChar::UnicodeVersion::Unicode_6_1)
            .define_value("Unicode_6_2", QChar::UnicodeVersion::Unicode_6_2)
            .define_value("Unicode_6_3", QChar::UnicodeVersion::Unicode_6_3)
            .define_value("Unicode_7_0", QChar::UnicodeVersion::Unicode_7_0)
            .define_value("Unicode_8_0", QChar::UnicodeVersion::Unicode_8_0)
            .define_value("Unicode_9_0", QChar::UnicodeVersion::Unicode_9_0)
            .define_value("Unicode_10_0", QChar::UnicodeVersion::Unicode_10_0)
            .define_value("Unicode_11_0", QChar::UnicodeVersion::Unicode_11_0)
            .define_value("Unicode_12_0", QChar::UnicodeVersion::Unicode_12_0)
            .define_value("Unicode_12_1", QChar::UnicodeVersion::Unicode_12_1)
            .define_value("Unicode_13_0", QChar::UnicodeVersion::Unicode_13_0)
            .define_value("Unicode_14_0", QChar::UnicodeVersion::Unicode_14_0)
            .define_value("Unicode_15_0", QChar::UnicodeVersion::Unicode_15_0)
            .define_value("Unicode_15_1", QChar::UnicodeVersion::Unicode_15_1)
            .define_value("Unicode_16_0", QChar::UnicodeVersion::Unicode_16_0);
}
