#include "qmetatype-rb.hpp"
#include <qmetatype.h>

using namespace Rice;

Rice::Class rb_cQMetaType;

void Init_qmetatype(Rice::Module rb_mQt6QtCore)
{
    rb_cQMetaType =
        // RubyQt6::QtCore::QMetaType
        define_class_under<QMetaType>(rb_mQt6QtCore, "QMetaType")
            // Constructor
            .define_constructor(Constructor<QMetaType, int>(), Arg("type_id"))
            // Public Functions
            .define_method("id", &QMetaType::id, Arg("_") = static_cast<int>(0))
            .define_method("name", &QMetaType::name);

    Enum<QMetaType::Type> rb_cQMetaTypeType =
        // RubyQt6::QtCore::QMetaType::Type
        define_enum_under<QMetaType::Type>("Type", rb_cQMetaType)
            .define_value("Bool", QMetaType::Type::Bool)
            .define_value("Char", QMetaType::Type::Char)
            .define_value("Char16", QMetaType::Type::Char16)
            .define_value("Char32", QMetaType::Type::Char32)
            .define_value("SChar", QMetaType::Type::SChar)
            .define_value("UChar", QMetaType::Type::UChar)
            .define_value("Int", QMetaType::Type::Int)
            .define_value("Long", QMetaType::Type::Long)
            .define_value("LongLong", QMetaType::Type::LongLong)
            .define_value("Short", QMetaType::Type::Short)
            .define_value("UInt", QMetaType::Type::UInt)
            .define_value("ULong", QMetaType::Type::ULong)
            .define_value("ULongLong", QMetaType::Type::ULongLong)
            .define_value("UShort", QMetaType::Type::UShort)
            .define_value("Double", QMetaType::Type::Double)
            .define_value("Float", QMetaType::Type::Float)
            .define_value("Float16", QMetaType::Type::Float16)
            .define_value("Nullptr", QMetaType::Type::Nullptr)
            .define_value("Void", QMetaType::Type::Void)
            .define_value("VoidStar", QMetaType::Type::VoidStar)
            .define_value("QObjectStar", QMetaType::Type::QObjectStar)
            .define_value("QBitArray", QMetaType::Type::QBitArray)
            .define_value("QBitmap", QMetaType::Type::QBitmap)
            .define_value("QBrush", QMetaType::Type::QBrush)
            .define_value("QByteArray", QMetaType::Type::QByteArray)
            .define_value("QByteArrayList", QMetaType::Type::QByteArrayList)
            .define_value("QCborArray", QMetaType::Type::QCborArray)
            .define_value("QCborMap", QMetaType::Type::QCborMap)
            .define_value("QCborSimpleType", QMetaType::Type::QCborSimpleType)
            .define_value("QCborValue", QMetaType::Type::QCborValue)
            .define_value("QChar", QMetaType::Type::QChar)
            .define_value("QColor", QMetaType::Type::QColor)
            .define_value("QColorSpace", QMetaType::Type::QColorSpace)
            .define_value("QCursor", QMetaType::Type::QCursor)
            .define_value("QDate", QMetaType::Type::QDate)
            .define_value("QDateTime", QMetaType::Type::QDateTime)
            .define_value("QEasingCurve", QMetaType::Type::QEasingCurve)
            .define_value("QFont", QMetaType::Type::QFont)
            .define_value("QIcon", QMetaType::Type::QIcon)
            .define_value("QImage", QMetaType::Type::QImage)
            .define_value("QJsonArray", QMetaType::Type::QJsonArray)
            .define_value("QJsonDocument", QMetaType::Type::QJsonDocument)
            .define_value("QJsonObject", QMetaType::Type::QJsonObject)
            .define_value("QJsonValue", QMetaType::Type::QJsonValue)
            .define_value("QKeySequence", QMetaType::Type::QKeySequence)
            .define_value("QLine", QMetaType::Type::QLine)
            .define_value("QLineF", QMetaType::Type::QLineF)
            .define_value("QLocale", QMetaType::Type::QLocale)
            .define_value("QMatrix4x4", QMetaType::Type::QMatrix4x4)
            .define_value("QModelIndex", QMetaType::Type::QModelIndex)
            .define_value("QPalette", QMetaType::Type::QPalette)
            .define_value("QPen", QMetaType::Type::QPen)
            .define_value("QPersistentModelIndex", QMetaType::Type::QPersistentModelIndex)
            .define_value("QPixmap", QMetaType::Type::QPixmap)
            .define_value("QPoint", QMetaType::Type::QPoint)
            .define_value("QPointF", QMetaType::Type::QPointF)
            .define_value("QPolygon", QMetaType::Type::QPolygon)
            .define_value("QPolygonF", QMetaType::Type::QPolygonF)
            .define_value("QQuaternion", QMetaType::Type::QQuaternion)
            .define_value("QRect", QMetaType::Type::QRect)
            .define_value("QRectF", QMetaType::Type::QRectF)
            .define_value("QRegion", QMetaType::Type::QRegion)
            .define_value("QRegularExpression", QMetaType::Type::QRegularExpression)
            .define_value("QSizePolicy", QMetaType::Type::QSizePolicy)
            .define_value("QSize", QMetaType::Type::QSize)
            .define_value("QSizeF", QMetaType::Type::QSizeF)
            .define_value("QStringList", QMetaType::Type::QStringList)
            .define_value("QString", QMetaType::Type::QString)
            .define_value("QTextFormat", QMetaType::Type::QTextFormat)
            .define_value("QTextLength", QMetaType::Type::QTextLength)
            .define_value("QTime", QMetaType::Type::QTime)
            .define_value("QTransform", QMetaType::Type::QTransform)
            .define_value("QUrl", QMetaType::Type::QUrl)
            .define_value("QUuid", QMetaType::Type::QUuid)
            .define_value("QVariantHash", QMetaType::Type::QVariantHash)
            .define_value("QVariantList", QMetaType::Type::QVariantList)
            .define_value("QVariantMap", QMetaType::Type::QVariantMap)
            .define_value("QVariantPair", QMetaType::Type::QVariantPair)
            .define_value("QVariant", QMetaType::Type::QVariant)
            .define_value("QVector2D", QMetaType::Type::QVector2D)
            .define_value("QVector3D", QMetaType::Type::QVector3D)
            .define_value("QVector4D", QMetaType::Type::QVector4D)
            .define_value("User", QMetaType::Type::User)
            .define_value("UnknownType", QMetaType::Type::UnknownType);
}
