# frozen_string_literal: true

require_relative "configuration"
require_relative "ducktyping"

require_relative "refinements/kernel"
require_relative "refinements/string"

require_relative "qtcore/private/_nodoc"
require_relative "qtcore/private/inflector"
require_relative "qtcore/private/metamethod"
require_relative "qtcore/private/metaobject"
require_relative "qtcore/private/signal"
require_relative "qtcore/private/signalmanager"

require_relative "qtcore/version"
require_relative "qtcore/qtcore"
require_relative "qtcore/qtcoreversion"
require_relative "qtcore/qt"

require_relative "qtcore/qmetamethod"
require_relative "qtcore/qmetaobject"
require_relative "qtcore/qmetaobjectbuilder"
require_relative "qtcore/qmetatype"

require_relative "qtcore/qanystringview"
require_relative "qtcore/qbytearray"
require_relative "qtcore/qchar"
require_relative "qtcore/qstring"
require_relative "qtcore/qiodevicebase"

require_relative "qtcore/qbasictimer"
require_relative "qtcore/qbool"
require_relative "qtcore/qevent"
require_relative "qtcore/qchildevent"
require_relative "qtcore/qdynamicpropertychangeevent"
require_relative "qtcore/qtimerevent"
require_relative "qtcore/qdatetime"
require_relative "qtcore/qdate"
require_relative "qtcore/qtime"
require_relative "qtcore/qdir"
require_relative "qtcore/qfileinfo"
require_relative "qtcore/qitemselectionrange"
require_relative "qtcore/qlibraryinfo"
require_relative "qtcore/qline"
require_relative "qtcore/qlinef"
require_relative "qtcore/qlocale"
require_relative "qtcore/qmargins"
require_relative "qtcore/qmarginsf"
require_relative "qtcore/qmodelindex"
require_relative "qtcore/qpoint"
require_relative "qtcore/qpointf"
require_relative "qtcore/qrect"
require_relative "qtcore/qrectf"
require_relative "qtcore/qregularexpression"
require_relative "qtcore/qregularexpressionmatch"
require_relative "qtcore/qresource"
require_relative "qtcore/qsize"
require_relative "qtcore/qsizef"
require_relative "qtcore/qtextstream"
require_relative "qtcore/qurl"
require_relative "qtcore/quuid"
require_relative "qtcore/qvariant"

require_relative "qtcore/qobject"
require_relative "qtcore/qcoreapplication"
require_relative "qtcore/qiodevice"
require_relative "qtcore/qfiledevice"
require_relative "qtcore/qfile"
require_relative "qtcore/qitemselectionmodel"
require_relative "qtcore/qsettings"
require_relative "qtcore/qsignalmapper"
require_relative "qtcore/qtimer"
require_relative "qtcore/qtranslator"

require_relative "qtcore/qitemselection"
require_relative "qtcore/qstringlist"

require_relative "bando/dsl"
require_relative "bando/qobject"
