# frozen_string_literal: true

require_relative "refinements/kernel"

require_relative "qtcore/private/_nodoc"
require_relative "qtcore/private/inflector"
require_relative "qtcore/private/metamethod"
require_relative "qtcore/private/metaobject"
require_relative "qtcore/private/signal"
require_relative "qtcore/private/signalmanager"

require_relative "qtcore/version"
require_relative "qtcore/qtcore"
require_relative "qtcore/qtcoreversion"
require_relative "qtcore/qt"

require_relative "qtcore/qchar"
require_relative "qtcore/qstring"
require_relative "qtcore/qanystringview"
require_relative "qtcore/qbytearray"
require_relative "qtcore/qdatetime"
require_relative "qtcore/qdate"
require_relative "qtcore/qtime"
require_relative "qtcore/qline"
require_relative "qtcore/qlinef"
require_relative "qtcore/qmargins"
require_relative "qtcore/qmarginsf"
require_relative "qtcore/qpoint"
require_relative "qtcore/qpointf"
require_relative "qtcore/qrect"
require_relative "qtcore/qrectf"
require_relative "qtcore/qsize"
require_relative "qtcore/qsizef"
require_relative "qtcore/qurl"
require_relative "qtcore/quuid"
require_relative "qtcore/qvariant"

require_relative "qtcore/qstringlist"

require_relative "qtcore/qmetaobjectbuilder"
require_relative "qtcore/qmetaobject"
require_relative "qtcore/qmetamethod"
require_relative "qtcore/qmetatype"

require_relative "qtcore/qobject"
require_relative "qtcore/qcoreapplication"

require_relative "bando/dsl"
require_relative "bando/qobject"
require_relative "bando/qcoreapplication"
