#include "qtwidgetspreludes-rb.hpp"

#include <QMetaObject>
#include <QByteArray>
#include <QString>
#include <QEvent>
#include <QDateTime>
#include <QDir>
#include <QFileInfo>
#include <QLine>
#include <QLineF>
#include <QLocale>
#include <QMargins>
#include <QMarginsF>
#include <QModelIndex>
#include <QPoint>
#include <QPointF>
#include <QPolygon>
#include <QPolygonF>
#include <QRect>
#include <QRectF>
#include <QRegularExpression>
#include <QSize>
#include <QSizeF>
#include <QUrl>
#include <QVariant>
#include <QObject>
#include <QAbstractItemModel>

#include <QBrush>
#include <QColor>
#include <QCursor>
#include <QFont>
#include <QFontInfo>
#include <QFontMetrics>
#include <QIcon>
#include <QKeySequence>
#include <QPaintDevice>
#include <QPagedPaintDevice>
#include <QPicture>
#include <QPixmap>
#include <QPainter>
#include <QPainterPath>
#include <QPalette>
#include <QPen>
#include <QRegion>
#include <QTextCursor>
#include <QAction>
#include <QMovie>
#include <QScreen>
#include <QTextDocument>
#include <QValidator>
#include <QWindow>

RICE4RUBYQT6_USE_NAMESPACE

void Init_qtwidgetspreludes(Module rb_mQt6)
{
    Module rb_mQt6QtCore = define_module_under(rb_mQt6, "QtCore");
    declare_qlass_under<QMetaObject>(rb_mQt6QtCore, "QMetaObject");
    declare_qlass_under<QByteArray>(rb_mQt6QtCore, "QByteArray");
    declare_qlass_under<QString>(rb_mQt6QtCore, "QString");
    declare_qlass_under<QEvent>(rb_mQt6QtCore, "QEvent");
    declare_qlass_under<QDateTime>(rb_mQt6QtCore, "QDateTime");
    declare_qlass_under<QDate>(rb_mQt6QtCore, "QDate");
    declare_qlass_under<QTime>(rb_mQt6QtCore, "QTime");
    declare_qlass_under<QDir>(rb_mQt6QtCore, "QDir");
    declare_qlass_under<QFileInfo>(rb_mQt6QtCore, "QFileInfo");
    declare_qlass_under<QLine>(rb_mQt6QtCore, "QLine");
    declare_qlass_under<QLineF>(rb_mQt6QtCore, "QLineF");
    declare_qlass_under<QLocale>(rb_mQt6QtCore, "QLocale");
    declare_qlass_under<QMargins>(rb_mQt6QtCore, "QMargins");
    declare_qlass_under<QMarginsF>(rb_mQt6QtCore, "QMarginsF");
    declare_qlass_under<QModelIndex>(rb_mQt6QtCore, "QModelIndex");
    declare_qlass_under<QPoint>(rb_mQt6QtCore, "QPoint");
    declare_qlass_under<QPointF>(rb_mQt6QtCore, "QPointF");
    declare_qlass_under<QPolygon>(rb_mQt6QtCore, "QPolygon");
    declare_qlass_under<QPolygonF>(rb_mQt6QtCore, "QPolygonF");
    declare_qlass_under<QRect>(rb_mQt6QtCore, "QRect");
    declare_qlass_under<QRectF>(rb_mQt6QtCore, "QRectF");
    declare_qlass_under<QRegularExpression>(rb_mQt6QtCore, "QRegularExpression");
    declare_qlass_under<QSize>(rb_mQt6QtCore, "QSize");
    declare_qlass_under<QSizeF>(rb_mQt6QtCore, "QSizeF");
    declare_qlass_under<QUrl>(rb_mQt6QtCore, "QUrl");
    declare_qlass_under<QVariant>(rb_mQt6QtCore, "QVariant");
    declare_qlass_under<QObject>(rb_mQt6QtCore, "QObject");
    declare_qlass_under<QAbstractItemModel>(rb_mQt6QtCore, "QAbstractItemModel");

    Module rb_mQt = define_module_under(rb_mQt6QtCore, "Qt");
    declare_qlass_under<Qt::AlignmentFlag>(rb_mQt, "AlignmentFlag");
    declare_qlass_under<Qt::ArrowType>(rb_mQt, "ArrowType");
    declare_qlass_under<Qt::AspectRatioMode>(rb_mQt, "AspectRatioMode");
    declare_qlass_under<Qt::CheckState>(rb_mQt, "CheckState");
    declare_qlass_under<Qt::ContextMenuPolicy>(rb_mQt, "ContextMenuPolicy");
    declare_qlass_under<Qt::Corner>(rb_mQt, "Corner");
    declare_qlass_under<Qt::CursorMoveStyle>(rb_mQt, "CursorMoveStyle");
    declare_qlass_under<Qt::DayOfWeek>(rb_mQt, "DayOfWeek");
    declare_qlass_under<Qt::DockWidgetArea>(rb_mQt, "DockWidgetArea");
    declare_qlass_under<Qt::DropAction>(rb_mQt, "DropAction");
    declare_qlass_under<Qt::FillRule>(rb_mQt, "FillRule");
    declare_qlass_under<Qt::FocusPolicy>(rb_mQt, "FocusPolicy");
    declare_qlass_under<Qt::FocusReason>(rb_mQt, "FocusReason");
    declare_qlass_under<Qt::GestureType>(rb_mQt, "GestureType");
    declare_qlass_under<Qt::ItemSelectionMode>(rb_mQt, "ItemSelectionMode");
    declare_qlass_under<Qt::ItemSelectionOperation>(rb_mQt, "ItemSelectionOperation");
    declare_qlass_under<Qt::LayoutDirection>(rb_mQt, "LayoutDirection");
    declare_qlass_under<Qt::Orientation>(rb_mQt, "Orientation");
    declare_qlass_under<Qt::PenStyle>(rb_mQt, "PenStyle");
    declare_qlass_under<Qt::ScrollBarPolicy>(rb_mQt, "ScrollBarPolicy");
    declare_qlass_under<Qt::ShortcutContext>(rb_mQt, "ShortcutContext");
    declare_qlass_under<Qt::SortOrder>(rb_mQt, "SortOrder");
    declare_qlass_under<Qt::TextElideMode>(rb_mQt, "TextElideMode");
    declare_qlass_under<Qt::TextFormat>(rb_mQt, "TextFormat");
    declare_qlass_under<Qt::ToolBarArea>(rb_mQt, "ToolBarArea");
    declare_qlass_under<Qt::ToolButtonStyle>(rb_mQt, "ToolButtonStyle");
    declare_qlass_under<Qt::TransformationMode>(rb_mQt, "TransformationMode");
    declare_qlass_under<Qt::UIEffect>(rb_mQt, "UIEffect");
    declare_qlass_under<Qt::WidgetAttribute>(rb_mQt, "WidgetAttribute");
    declare_qlass_under<Qt::WindowModality>(rb_mQt, "WindowModality");
    declare_qlass_under<Qt::WindowType>(rb_mQt, "WindowType");
    declare_qlass_under<QFlags<Qt::AlignmentFlag>>(rb_mQt, "Alignment");
    declare_qlass_under<QFlags<Qt::DockWidgetArea>>(rb_mQt, "DockWidgetAreas");
    declare_qlass_under<QFlags<Qt::FindChildOption>>(rb_mQt, "FindChildOptions");
    declare_qlass_under<QFlags<Qt::GestureFlag>>(rb_mQt, "GestureFlags");
    declare_qlass_under<QFlags<Qt::ItemFlag>>(rb_mQt, "ItemFlags");
    declare_qlass_under<QFlags<Qt::InputMethodHint>>(rb_mQt, "InputMethodHints");
    declare_qlass_under<QFlags<Qt::KeyboardModifier>>(rb_mQt, "KeyboardModifiers");
    declare_qlass_under<QFlags<Qt::MatchFlag>>(rb_mQt, "MatchFlags");
    declare_qlass_under<QFlags<Qt::MouseButton>>(rb_mQt, "MouseButtons");
    declare_qlass_under<QFlags<Qt::Orientation>>(rb_mQt, "Orientations");
    declare_qlass_under<QFlags<Qt::TextInteractionFlag>>(rb_mQt, "TextInteractionFlags");
    declare_qlass_under<QFlags<Qt::ToolBarArea>>(rb_mQt, "ToolBarAreas");
    declare_qlass_under<QFlags<Qt::WindowState>>(rb_mQt, "WindowStates");
    declare_qlass_under<QFlags<Qt::WindowType>>(rb_mQt, "WindowFlags");

    Module rb_mQt6QtGui = define_module_under(rb_mQt6, "QtGui");
    declare_qlass_under<QBrush>(rb_mQt6QtGui, "QBrush");
    declare_qlass_under<QColor>(rb_mQt6QtGui, "QColor");
    declare_qlass_under<QCursor>(rb_mQt6QtGui, "QCursor");
    declare_qlass_under<QFont>(rb_mQt6QtGui, "QFont");
    declare_qlass_under<QFontInfo>(rb_mQt6QtGui, "QFontInfo");
    declare_qlass_under<QFontMetrics>(rb_mQt6QtGui, "QFontMetrics");
    declare_qlass_under<QIcon>(rb_mQt6QtGui, "QIcon");
    declare_qlass_under<QKeySequence>(rb_mQt6QtGui, "QKeySequence");
    declare_qlass_under<QPaintDevice>(rb_mQt6QtGui, "QPaintDevice");
    declare_qlass_under<QPagedPaintDevice>(rb_mQt6QtGui, "QPagedPaintDevice");
    declare_qlass_under<QPicture>(rb_mQt6QtGui, "QPicture");
    declare_qlass_under<QPixmap>(rb_mQt6QtGui, "QPixmap");
    declare_qlass_under<QPainter>(rb_mQt6QtGui, "QPainter");
    declare_qlass_under<QPainterPath>(rb_mQt6QtGui, "QPainterPath");
    declare_qlass_under<QPalette>(rb_mQt6QtGui, "QPalette");
    declare_qlass_under<QPen>(rb_mQt6QtGui, "QPen");
    declare_qlass_under<QRegion>(rb_mQt6QtGui, "QRegion");
    declare_qlass_under<QTextCursor>(rb_mQt6QtGui, "QTextCursor");
    declare_qlass_under<QAction>(rb_mQt6QtGui, "QAction");
    declare_qlass_under<QMovie>(rb_mQt6QtGui, "QMovie");
    declare_qlass_under<QScreen>(rb_mQt6QtGui, "QScreen");
    declare_qlass_under<QTextDocument>(rb_mQt6QtGui, "QTextDocument");
    declare_qlass_under<QValidator>(rb_mQt6QtGui, "QValidator");
    declare_qlass_under<QWindow>(rb_mQt6QtGui, "QWindow");

    Class rb_cQDir = rb_mQt6QtCore.const_get("QDir").value();
    declare_qlass_under<QFlags<QDir::Filter>>(rb_cQDir, "Filters");
}
