// clang-format off

#include "qwidget-rb.hpp"
#include <QtCore/QLocale>
#include <QtGui/QBackingStore>
#include <QtGui/QPaintEngine>
#include <QGraphicsEffect>
#include <QGraphicsProxyWidget>
#include <QLayout>
#include <QStyle>
#include <QWidget>

using namespace Rice;

Rice::Class rb_cQWidget;

void Init_QWidget(Rice::Module rb_mQt6QtWidgets)
{
    rb_cQWidget =
        // Qt6::QtWidgets::QWidget
        define_class_under<QWidget, QObject>(rb_mQt6QtWidgets, "QWidget")
            // Public Functions
            .define_constructor(Constructor<QWidget, QWidget *, Qt::WindowFlags>(), Arg("parent") = static_cast<QWidget *>(nullptr), Arg("f") = static_cast<Qt::WindowFlags>(Qt::WindowFlags()))
            .define_method("accept_drops", &QWidget::acceptDrops)
            .define_method("accessible_description", &QWidget::accessibleDescription)
            .define_method("accessible_identifier", &QWidget::accessibleIdentifier)
            .define_method("accessible_name", &QWidget::accessibleName)
            .define_method("actions", &QWidget::actions)
            .define_method("activate_window", &QWidget::activateWindow)
            .define_method("add_actions", &QWidget::addActions, Arg("actions"))
            .define_method<QAction *(QWidget::*)(const QIcon &, const QString &)>("add_action", &QWidget::addAction, Arg("icon"), Arg("text"))
            .define_method<QAction *(QWidget::*)(const QIcon &, const QString &, const QKeySequence &)>("add_action", &QWidget::addAction, Arg("icon"), Arg("text"), Arg("shortcut"))
            .define_method<QAction *(QWidget::*)(const QIcon &, const QString &, const QKeySequence &, const QObject *, const char *, Qt::ConnectionType)>( "add_action", &QWidget::addAction, Arg("icon"), Arg("text"), Arg("shortcut"), Arg("receiver"), Arg("member"), Arg("type") = static_cast<Qt::ConnectionType>(Qt::AutoConnection))
            .define_method<QAction *(QWidget::*)(const QIcon &, const QString &, const QObject *, const char *, Qt::ConnectionType)>( "add_action", &QWidget::addAction, Arg("icon"), Arg("text"), Arg("receiver"), Arg("member"), Arg("type") = static_cast<Qt::ConnectionType>(Qt::AutoConnection))
            .define_method<QAction *(QWidget::*)(const QString &)>("add_action", &QWidget::addAction, Arg("text"))
            .define_method<QAction *(QWidget::*)(const QString &, const QKeySequence &)>("add_action", &QWidget::addAction, Arg("text"), Arg("shortcut"))
            .define_method<QAction *(QWidget::*)(const QString &, const QKeySequence &, const QObject *, const char *, Qt::ConnectionType)>("add_action", &QWidget::addAction, Arg("text"), Arg("shortcut"), Arg("receiver"), Arg("member"), Arg("type") = static_cast<Qt::ConnectionType>(Qt::AutoConnection))
            .define_method<QAction *(QWidget::*)(const QString &, const QObject *, const char *, Qt::ConnectionType)>("add_action", &QWidget::addAction, Arg("text"), Arg("receiver"), Arg("member"), Arg("type") = static_cast<Qt::ConnectionType>(Qt::AutoConnection))
            .define_method<void (QWidget::*)(QAction *)>("add_action", &QWidget::addAction, Arg("action"))
            .define_method("adjust_size", &QWidget::adjustSize)
            .define_method("auto_fill_background", &QWidget::autoFillBackground)
            .define_method("background_role", &QWidget::backgroundRole)
            .define_method("backing_store", &QWidget::backingStore)
            .define_method("base_size", &QWidget::baseSize)
            .define_method<QWidget *(QWidget::*)(const QPoint &) const>("child_at", &QWidget::childAt, Arg("p"))
            .define_method<QWidget *(QWidget::*)(const QPointF &) const>("child_at", &QWidget::childAt, Arg("p"))
            .define_method<QWidget *(QWidget::*)(int, int) const>("child_at", &QWidget::childAt, Arg("x"), Arg("y"))
            .define_method("children_rect", &QWidget::childrenRect)
            .define_method("children_region", &QWidget::childrenRegion)
            .define_method("clear_focus", &QWidget::clearFocus)
            .define_method("clear_mask", &QWidget::clearMask)
            .define_method("contents_margins", &QWidget::contentsMargins)
            .define_method("contents_rect", &QWidget::contentsRect)
            .define_method("context_menu_policy", &QWidget::contextMenuPolicy)
            .define_method("create_win_id", &QWidget::createWinId)
            .define_method("cursor", &QWidget::cursor)
            .define_method("dev_type", &QWidget::devType)
            .define_method("effective_win_id", &QWidget::effectiveWinId)
            .define_method("ensure_polished", &QWidget::ensurePolished)
            .define_method("focus_policy", &QWidget::focusPolicy)
            .define_method("focus_proxy", &QWidget::focusProxy)
            .define_method("focus_widget", &QWidget::focusWidget)
            .define_method("font_info", &QWidget::fontInfo)
            .define_method("font_metrics", &QWidget::fontMetrics)
            .define_method("font", &QWidget::font)
            .define_method("foreground_role", &QWidget::foregroundRole)
            .define_method("frame_geometry", &QWidget::frameGeometry)
            .define_method("frame_size", &QWidget::frameSize)
            .define_method("geometry", &QWidget::geometry)
            .define_method("grab_gesture", &QWidget::grabGesture, Arg("type"), Arg("flags") = static_cast<Qt::GestureFlags>(Qt::GestureFlags()))
            .define_method("grab_keyboard", &QWidget::grabKeyboard)
            .define_method<void (QWidget::*)(const QCursor &)>("grab_mouse", &QWidget::grabMouse, Arg(""))
            .define_method<void (QWidget::*)()>("grab_mouse", &QWidget::grabMouse)
            .define_method("grab_shortcut", &QWidget::grabShortcut, Arg("key"), Arg("context") = static_cast<Qt::ShortcutContext>(Qt::WindowShortcut)) .define_method("release_shortcut", &QWidget::releaseShortcut, Arg("id"))
            .define_method("grab", &QWidget::grab, Arg("rectangle") = static_cast<const QRect &>(QRect(QPoint(0, 0), QSize(-1, -1))))
            .define_method("graphics_effect", &QWidget::graphicsEffect)
            .define_method("graphics_proxy_widget", &QWidget::graphicsProxyWidget)
            .define_method("has_focus", &QWidget::hasFocus)
            .define_method("has_height_for_width", &QWidget::hasHeightForWidth)
            .define_method("has_mouse_tracking", &QWidget::hasMouseTracking)
            .define_method("has_tablet_tracking", &QWidget::hasTabletTracking)
            .define_method("height_for_width", &QWidget::heightForWidth, Arg(""))
            .define_method("height", &QWidget::height)
            .define_method("input_method_hints", &QWidget::inputMethodHints)
            .define_method("input_method_query", &QWidget::inputMethodQuery, Arg(""))
            .define_method("insert_action", &QWidget::insertAction, Arg("before"), Arg("action"))
            .define_method("insert_actions", &QWidget::insertActions, Arg("before"), Arg("actions"))
            .define_method("internal_win_id", &QWidget::internalWinId)
            .define_method("is_active_window", &QWidget::isActiveWindow)
            .define_method("is_ancestor_of", &QWidget::isAncestorOf, Arg("child"))
            .define_method("is_enabled", &QWidget::isEnabled)
            .define_method("is_enabled_to", &QWidget::isEnabledTo, Arg(""))
            .define_method("is_full_screen", &QWidget::isFullScreen)
            .define_method("is_hidden", &QWidget::isHidden)
            .define_method("is_left_to_right", &QWidget::isLeftToRight)
            .define_method("is_maximized", &QWidget::isMaximized)
            .define_method("is_minimized", &QWidget::isMinimized)
            .define_method("is_modal", &QWidget::isModal)
            .define_method("is_right_to_left", &QWidget::isRightToLeft)
            .define_method("is_visible", &QWidget::isVisible)
            .define_method("is_visible_to", &QWidget::isVisibleTo, Arg(""))
            .define_method("is_window_modified", &QWidget::isWindowModified)
            .define_method("is_window", &QWidget::isWindow)
            .define_method("layout_direction", &QWidget::layoutDirection)
            .define_method("layout", &QWidget::layout)
            .define_method("locale", &QWidget::locale)
            .define_method<QPointF (QWidget::*)(const QWidget *, const QPointF &) const>("map_from", &QWidget::mapFrom, Arg(""), Arg("")) .define_method<QPoint (QWidget::*)(const QWidget *, const QPoint &) const>("map_from", &QWidget::mapFrom, Arg(""), Arg(""))
            .define_method<QPointF (QWidget::*)(const QPointF &) const>("map_from_global", &QWidget::mapFromGlobal, Arg(""))
            .define_method<QPoint (QWidget::*)(const QPoint &) const>("map_from_global", &QWidget::mapFromGlobal, Arg(""))
            .define_method<QPointF (QWidget::*)(const QPointF &) const>("map_from_parent", &QWidget::mapFromParent, Arg(""))
            .define_method<QPoint (QWidget::*)(const QPoint &) const>("map_from_parent", &QWidget::mapFromParent, Arg(""))
            .define_method<QPointF (QWidget::*)(const QWidget *, const QPointF &) const>("map_to", &QWidget::mapTo, Arg(""), Arg(""))
            .define_method<QPoint (QWidget::*)(const QWidget *, const QPoint &) const>("map_to", &QWidget::mapTo, Arg(""), Arg(""))
            .define_method<QPoint (QWidget::*)(const QPoint &) const>("map_to_global", &QWidget::mapToGlobal, Arg(""))
            .define_method<QPointF (QWidget::*)(const QPointF &) const>("map_to_global", &QWidget::mapToGlobal, Arg(""))
            .define_method<QPointF (QWidget::*)(const QPointF &) const>("map_to_parent", &QWidget::mapToParent, Arg(""))
            .define_method<QPoint (QWidget::*)(const QPoint &) const>("map_to_parent", &QWidget::mapToParent, Arg(""))
            .define_method("mask", &QWidget::mask)
            .define_method("maximum_height", &QWidget::maximumHeight)
            .define_method("maximum_size", &QWidget::maximumSize)
            .define_method("maximum_width", &QWidget::maximumWidth)
            .define_method("minimum_height", &QWidget::minimumHeight)
            .define_method("minimum_size_hint", &QWidget::minimumSizeHint)
            .define_method("minimum_size", &QWidget::minimumSize)
            .define_method("minimum_width", &QWidget::minimumWidth)
            .define_method<void (QWidget::*)(const QPoint &)>("move", &QWidget::move, Arg(""))
            .define_method<void (QWidget::*)(int, int)>("move", &QWidget::move, Arg("x"), Arg("y"))
            .define_method("native_parent_widget", &QWidget::nativeParentWidget)
            .define_method("next_in_focus_chain", &QWidget::nextInFocusChain)
            .define_method("normal_geometry", &QWidget::normalGeometry)
            .define_method("override_window_flags", &QWidget::overrideWindowFlags, Arg("type"))
            .define_method("override_window_state", &QWidget::overrideWindowState, Arg("state"))
            .define_method("palette", &QWidget::palette)
            .define_method("parent_widget", &QWidget::parentWidget)
            .define_method("pos", &QWidget::pos)
            .define_method("previous_in_focus_chain", &QWidget::previousInFocusChain)
            .define_method("rect", &QWidget::rect)
            .define_method("release_keyboard", &QWidget::releaseKeyboard)
            .define_method("release_mouse", &QWidget::releaseMouse)
            .define_method("remove_action", &QWidget::removeAction, Arg("action"))
            // .define_method<void (QWidget::*)(QPaintDevice *, const QPoint &, const QRegion &, QWidget::RenderFlags)>("render", &QWidget::render, Arg("target"), Arg("target_offset") = static_cast<const QPoint &>(QPoint()), Arg("source_region") = static_cast<const QRegion &>(QRegion()), Arg("render_flags") = static_cast<RenderFlags>(RenderFlags(DrawWindowBackground | DrawChildren)))
            // .define_method<void (QWidget::*)(QPainter *, const QPoint &, const QRegion &, QWidget::RenderFlags)>("render", &QWidget::render, Arg("painter"), Arg("target_offset") = static_cast<const QPoint &>(QPoint()), Arg("source_region") = static_cast<const QRegion &>(QRegion()), Arg("render_flags") = static_cast<RenderFlags>(RenderFlags(DrawWindowBackground | DrawChildren)))
            .define_method<void (QWidget::*)(const QRect &)>("repaint", &QWidget::repaint, Arg(""))
            .define_method<void (QWidget::*)(const QRegion &)>("repaint", &QWidget::repaint, Arg(""))
            .define_method<void (QWidget::*)(int, int, int, int)>("repaint", &QWidget::repaint, Arg("x"), Arg("y"), Arg("w"), Arg("h"))
            .define_method<void (QWidget::*)(const QSize &)>("resize", &QWidget::resize, Arg(""))
            .define_method<void (QWidget::*)(int, int)>("resize", &QWidget::resize, Arg("w"), Arg("h"))
            .define_method("restore_geometry", &QWidget::restoreGeometry, Arg("geometry"))
            .define_method("save_geometry", &QWidget::saveGeometry)
            .define_method("screen", &QWidget::screen)
            .define_method<void (QWidget::*)(int, int, const QRect &)>("scroll", &QWidget::scroll, Arg("dx"), Arg("dy"), Arg(""))
            .define_method<void (QWidget::*)(int, int)>("scroll", &QWidget::scroll, Arg("dx"), Arg("dy"))
            .define_method("set_accept_drops", &QWidget::setAcceptDrops, Arg("on"))
            .define_method("set_accessible_description", &QWidget::setAccessibleDescription, Arg("description"))
            .define_method("set_accessible_identifier", &QWidget::setAccessibleIdentifier, Arg("identifier"))
            .define_method("set_accessible_name", &QWidget::setAccessibleName, Arg("name"))
            .define_method("set_attribute", &QWidget::setAttribute, Arg(""), Arg("on") = static_cast<bool>(true))
            .define_method("set_auto_fill_background", &QWidget::setAutoFillBackground, Arg("enabled"))
            .define_method("set_background_role", &QWidget::setBackgroundRole, Arg(""))
            .define_method<void (QWidget::*)(const QSize &)>("set_base_size", &QWidget::setBaseSize, Arg(""))
            .define_method<void (QWidget::*)(int, int)>("set_base_size", &QWidget::setBaseSize, Arg("basew"), Arg("baseh"))
            .define_method<void (QWidget::*)(const QMargins &)>("set_contents_margins", &QWidget::setContentsMargins, Arg("margins"))
            .define_method<void (QWidget::*)(int, int, int, int)>("set_contents_margins", &QWidget::setContentsMargins, Arg("left"), Arg("top"), Arg("right"), Arg("bottom"))
            .define_method("set_context_menu_policy", &QWidget::setContextMenuPolicy, Arg("policy"))
            .define_method("set_cursor", &QWidget::setCursor, Arg(""))
            .define_method("set_enabled", &QWidget::setEnabled, Arg(""))
            .define_method("set_fixed_height", &QWidget::setFixedHeight, Arg("h"))
            .define_method<void (QWidget::*)(const QSize &)>("set_fixed_size", &QWidget::setFixedSize, Arg(""))
            .define_method<void (QWidget::*)(int, int)>("set_fixed_size", &QWidget::setFixedSize, Arg("w"), Arg("h"))
            .define_method("set_fixed_width", &QWidget::setFixedWidth, Arg("w"))
            .define_method<void (QWidget::*)(Qt::FocusReason)>("set_focus", &QWidget::setFocus, Arg("reason"))
            .define_method("set_focus_policy", &QWidget::setFocusPolicy, Arg("policy"))
            .define_method("set_focus_proxy", &QWidget::setFocusProxy, Arg(""))
            .define_method("set_font", &QWidget::setFont, Arg(""))
            .define_method("set_foreground_role", &QWidget::setForegroundRole, Arg(""))
            .define_method<void (QWidget::*)(const QRect &)>("set_geometry", &QWidget::setGeometry, Arg(""))
            .define_method<void (QWidget::*)(int, int, int, int)>("set_geometry", &QWidget::setGeometry, Arg("x"), Arg("y"), Arg("w"), Arg("h"))
            .define_method("set_graphics_effect", &QWidget::setGraphicsEffect, Arg("effect"))
            .define_method("set_input_method_hints", &QWidget::setInputMethodHints, Arg("hints"))
            .define_method("set_input_method_hints", &QWidget::setInputMethodHints, Arg("hints"))
            .define_method("set_layout_direction", &QWidget::setLayoutDirection, Arg("direction"))
            .define_method("set_layout", &QWidget::setLayout, Arg(""))
            .define_method("set_locale", &QWidget::setLocale, Arg("locale"))
            .define_method<void (QWidget::*)(const QBitmap &)>("set_mask", &QWidget::setMask, Arg(""))
            .define_method<void (QWidget::*)(const QRegion &)>("set_mask", &QWidget::setMask, Arg(""))
            .define_method("set_maximum_height", &QWidget::setMaximumHeight, Arg("maxh"))
            .define_method<void (QWidget::*)(const QSize &)>("set_maximum_size", &QWidget::setMaximumSize, Arg(""))
            .define_method<void (QWidget::*)(int, int)>("set_maximum_size", &QWidget::setMaximumSize, Arg("maxw"), Arg("maxh"))
            .define_method("set_maximum_width", &QWidget::setMaximumWidth, Arg("maxw"))
            .define_method("set_minimum_height", &QWidget::setMinimumHeight, Arg("minh"))
            .define_method<void (QWidget::*)(const QSize &)>("set_minimum_size", &QWidget::setMinimumSize, Arg(""))
            .define_method<void (QWidget::*)(int, int)>("set_minimum_size", &QWidget::setMinimumSize, Arg("minw"), Arg("minh"))
            .define_method("set_minimum_width", &QWidget::setMinimumWidth, Arg("minw"))
            .define_method("set_mouse_tracking", &QWidget::setMouseTracking, Arg("enable"))
            .define_method("set_palette", &QWidget::setPalette, Arg(""))
            .define_method<void (QWidget::*)(QWidget *, Qt::WindowFlags)>("set_parent", &QWidget::setParent, Arg("parent"), Arg("f"))
            .define_method<void (QWidget::*)(QWidget *)>("set_parent", &QWidget::setParent, Arg("parent"))
            .define_method("set_screen", &QWidget::setScreen, Arg(""))
            .define_method("set_shortcut_auto_repeat", &QWidget::setShortcutAutoRepeat, Arg("id"), Arg("enable") = static_cast<bool>(true))
            .define_method("set_shortcut_enabled", &QWidget::setShortcutEnabled, Arg("id"), Arg("enable") = static_cast<bool>(true))
            .define_method<void (QWidget::*)(const QSize &)>("set_size_increment", &QWidget::setSizeIncrement, Arg(""))
            .define_method<void (QWidget::*)(int, int)>("set_size_increment", &QWidget::setSizeIncrement, Arg("w"), Arg("h"))
            .define_method<void (QWidget::*)(QSizePolicy::Policy, QSizePolicy::Policy)>("set_size_policy", &QWidget::setSizePolicy, Arg("horizontal"), Arg("vertical"))
            .define_method<void (QWidget::*)(QSizePolicy)>("set_size_policy", &QWidget::setSizePolicy, Arg(""))
            .define_method("set_status_tip", &QWidget::setStatusTip, Arg(""))
            .define_method("set_style", &QWidget::setStyle, Arg(""))
            .define_method("set_tablet_tracking", &QWidget::setTabletTracking, Arg("enable"))
            .define_method("set_tool_tip_duration", &QWidget::setToolTipDuration, Arg("msec"))
            .define_method("set_tool_tip", &QWidget::setToolTip, Arg(""))
            .define_method("set_updates_enabled", &QWidget::setUpdatesEnabled, Arg("enable"))
            .define_method("set_whats_this", &QWidget::setWhatsThis, Arg(""))
            .define_method("set_window_file_path", &QWidget::setWindowFilePath, Arg("file_path"))
            .define_method("set_window_flag", &QWidget::setWindowFlag, Arg(""), Arg("on") = static_cast<bool>(true))
            .define_method("set_window_flags", &QWidget::setWindowFlags, Arg("type"))
            .define_method("set_window_icon", &QWidget::setWindowIcon, Arg("icon"))
            .define_method("set_window_modality", &QWidget::setWindowModality, Arg("window_modality"))
            .define_method("set_window_opacity", &QWidget::setWindowOpacity, Arg("level"))
            .define_method("set_window_role", &QWidget::setWindowRole, Arg(""))
            .define_method("set_window_state", &QWidget::setWindowState, Arg("state"))
            .define_method("size_hint", &QWidget::sizeHint)
            .define_method("size_increment", &QWidget::sizeIncrement)
            .define_method("size_policy", &QWidget::sizePolicy)
            .define_method("size", &QWidget::size)
            .define_method("stack_under", &QWidget::stackUnder, Arg(""))
            .define_method("status_tip", &QWidget::statusTip)
            .define_method("style", &QWidget::style)
            .define_method("style_sheet", &QWidget::styleSheet)
            .define_method("test_attribute", &QWidget::testAttribute, Arg(""))
            .define_method("tool_tip_duration", &QWidget::toolTipDuration)
            .define_method("tool_tip", &QWidget::toolTip)
            .define_method("under_mouse", &QWidget::underMouse)
            .define_method("ungrab_gesture", &QWidget::ungrabGesture, Arg("type"))
            .define_method("unset_cursor", &QWidget::unsetCursor)
            .define_method("unset_layout_direction", &QWidget::unsetLayoutDirection)
            .define_method("unset_locale", &QWidget::unsetLocale)
            .define_method<void (QWidget::*)(const QRect &)>("update", &QWidget::update, Arg(""))
            .define_method<void (QWidget::*)(const QRegion &)>("update", &QWidget::update, Arg(""))
            .define_method<void (QWidget::*)(int, int, int, int)>("update", &QWidget::update, Arg("x"), Arg("y"), Arg("w"), Arg("h"))
            .define_method("update_geometry", &QWidget::updateGeometry)
            .define_method("updates_enabled", &QWidget::updatesEnabled)
            .define_method("visible_region", &QWidget::visibleRegion)
            .define_method("whats_this", &QWidget::whatsThis)
            .define_method("width", &QWidget::width)
            .define_method("window_file_path", &QWidget::windowFilePath)
            .define_method("window_flags", &QWidget::windowFlags)
            .define_method("window_handle", &QWidget::windowHandle)
            .define_method("window_icon", &QWidget::windowIcon)
            .define_method("window_modality", &QWidget::windowModality)
            .define_method("window_opacity", &QWidget::windowOpacity)
            .define_method("window", &QWidget::window)
            .define_method("window_role", &QWidget::windowRole)
            .define_method("window_state", &QWidget::windowState)
            .define_method("window_title", &QWidget::windowTitle)
            .define_method("window_type", &QWidget::windowType)
            .define_method("win_id", &QWidget::winId)
            .define_method("x", &QWidget::x)
            .define_method("y", &QWidget::y)
            // Reimplemented Public Functions
            .define_method("paint_engine", &QWidget::paintEngine)
            // Public Slots
            .define_method("close", &QWidget::close)
            .define_method("hide", &QWidget::hide)
            .define_method("lower", &QWidget::lower)
            .define_method("raise", &QWidget::raise)
            .define_method<void (QWidget::*)()>("repaint", &QWidget::repaint)
            .define_method("set_disabled", &QWidget::setDisabled, Arg(""))
            .define_method<void (QWidget::*)()>("set_focus", &QWidget::setFocus)
            .define_method("set_hidden", &QWidget::setHidden, Arg("hidden"))
            .define_method("set_style_sheet", &QWidget::setStyleSheet, Arg("style_sheet"))
            .define_method("set_visible", &QWidget::setVisible, Arg("visible"))
            .define_method("set_window_modified", &QWidget::setWindowModified, Arg(""))
            .define_method("set_window_title", &QWidget::setWindowTitle, Arg(""))
            .define_method("show", &QWidget::show)
            .define_method("show_full_screen", &QWidget::showFullScreen)
            .define_method("show_maximized", &QWidget::showMaximized)
            .define_method("show_minimized", &QWidget::showMinimized)
            .define_method("show_normal", &QWidget::showNormal)
            .define_method<void (QWidget::*)()>("update", &QWidget::update)
            // Signals
            .define_method("custom_context_menu_requested", &QWidget::customContextMenuRequested, Arg("pos"))
            .define_method("window_icon_changed", &QWidget::windowIconChanged, Arg("icon"))
            .define_method("window_title_changed", &QWidget::windowTitleChanged, Arg("title"))
            // Static Public Members
            .define_singleton_function("create_window_container", &QWidget::createWindowContainer, Arg("window"), Arg("parent") = static_cast<QWidget *>(nullptr), Arg("flags") = static_cast<Qt::WindowFlags>(Qt::WindowFlags()))
            .define_singleton_function("find", &QWidget::find, Arg(""))
            .define_singleton_function("mouse_grabber", &QWidget::mouseGrabber)
            .define_singleton_function("keyboard_grabber", &QWidget::keyboardGrabber);
            // .define_singleton_function("set_tab_order", &QWidget::setTabOrder, Arg("widgets"))
            // .define_singleton_function<void (*)(QWidget *, QWidget *)>("set_tab_order", &QWidget::setTabOrder, Arg(""), Arg(""))

    Enum<QWidget::RenderFlag> rb_cQWidgetRenderFlag =
        // Qt6::QtWidgets::QWidget::RenderFlag
        define_enum_under<QWidget::RenderFlag>("RenderFlag", rb_cQWidget)
            .define_value("DrawWindowBackground", QWidget::RenderFlag::DrawWindowBackground)
            .define_value("DrawChildren", QWidget::RenderFlag::DrawChildren)
            .define_value("IgnoreMask", QWidget::RenderFlag::IgnoreMask);
}
